continent_to_adjective(africa, african).
continent_to_adjective(asia, asian).
continent_to_adjective(europe, european).
continent_to_adjective(central_america, central_american).
continent_to_adjective(middle_east, middle_eastern).
continent_to_adjective(north_africa, north_african).
continent_to_adjective(north_america, north_american).
continent_to_adjective(south_america, south_american).
continent_to_adjective(southeast_asia, southeast_asian).
nation_to_nationality(afghanistan, afghan).
nation_to_nationality(algeria, algerian).
nation_to_nationality(angola, angolan).
nation_to_nationality(argentina, argentine).
nation_to_nationality(austria, austrian).
nation_to_nationality(australia, australian).
nation_to_nationality(bangladesh, bangladeshi).
nation_to_nationality(belarus, belarusian).
nation_to_nationality(belgium, belgian).
nation_to_nationality(bolivia, bolivian).
nation_to_nationality(bosnia_and_herzegovina, bosnian-herzegovinian).
nation_to_nationality(brazil, brazilian).
nation_to_nationality(britain, british).
nation_to_nationality(bulgaria, bulgarian).
nation_to_nationality(cambodia, cambodian).
nation_to_nationality(cameroon, cameroonian).
nation_to_nationality(canada, canadian).
nation_to_nationality(central_african_republic, central_african).
nation_to_nationality(chad, chadian).
nation_to_nationality(china, chinese).
nation_to_nationality(colombia, colombian).
nation_to_nationality(costa_rica, costa_rican).
nation_to_nationality(croatia, croatian).
nation_to_nationality(the_czech_republic, czech).
nation_to_nationality(democratic_republic_of_the_congo, congolese).
nation_to_nationality(denmark, danish).
nation_to_nationality(ecuador, ecuadorian).
nation_to_nationality(egypt, egyptian).
nation_to_nationality(el_salvador, salvadoran).
nation_to_nationality(england, english).
nation_to_nationality(estonia, estonian).
nation_to_nationality(ethiopia, ethiopian).
nation_to_nationality(finland, finnish).
nation_to_nationality(france, french).
nation_to_nationality(germany, german).
nation_to_nationality(ghana, ghanaian).
nation_to_nationality(greece, greek).
nation_to_nationality(guatemala, guatemalan).
nation_to_nationality(holland, dutch).
nation_to_nationality(honduras, honduran).
nation_to_nationality(hungary, hungarian).
nation_to_nationality(iceland, icelandic).
nation_to_nationality(india, indian).
nation_to_nationality(indonesia, indonesian).
nation_to_nationality(iran, iranian).
nation_to_nationality(iraq, iraqi).
nation_to_nationality(ireland, irish).
nation_to_nationality(israel, israeli).
nation_to_nationality(italy, italian).
nation_to_nationality(ivory_coast, ivorian).
nation_to_nationality(jamaica, jamaican).
nation_to_nationality(japan, japanese).
nation_to_nationality(jordan, jordanian).
nation_to_nationality(kazakhstan, kazakh).
nation_to_nationality(kenya, kenyan).
nation_to_nationality(korea, korean).
nation_to_nationality(laos, lao).
nation_to_nationality(latvia, latvian).
nation_to_nationality(libya, libyan).
nation_to_nationality(lithuania, lithuanian).
nation_to_nationality(madagascar, malagasy).
nation_to_nationality(malaysia, malaysian).
nation_to_nationality(mali, malian).
nation_to_nationality(mauritania, mauritanian).
nation_to_nationality(mexico, mexican).
nation_to_nationality(morocco, moroccan).
nation_to_nationality(namibia, namibian).
nation_to_nationality(new_zealand, new_zealand).
nation_to_nationality(nicaragua, nicaraguan).
nation_to_nationality(niger, nigerien).
nation_to_nationality(nigeria, nigerian).
nation_to_nationality(norway, norwegian).
nation_to_nationality(oman, omani).
nation_to_nationality(pakistan, pakistani).
nation_to_nationality(panama, panamanian).
nation_to_nationality(paraguay, paraguayan).
nation_to_nationality(peru, peruvian).
nation_to_nationality(the_philippines, philippine).
nation_to_nationality(poland, polish).
nation_to_nationality(portugal, portuguese).
nation_to_nationality(republic_of_the_congo, congolese).
nation_to_nationality(romania, romanian).
nation_to_nationality(russia, russian).
nation_to_nationality(saudi_arabia, saudi_arabian).
nation_to_nationality(scotland, scottish).
nation_to_nationality(senegal, senegalese).
nation_to_nationality(serbia, serbian).
nation_to_nationality(singapore, singaporean).
nation_to_nationality(slovakia, slovak).
nation_to_nationality(somalia, somalian).
nation_to_nationality(south_africa, south_african).
nation_to_nationality(spain, spanish).
nation_to_nationality(sudan, sudanese).
nation_to_nationality(sweden, swedish).
nation_to_nationality(switzerland, swiss).
nation_to_nationality(syria, syrian).
nation_to_nationality(thailand, thai).
nation_to_nationality(tunisia, tunisian).
nation_to_nationality(turkey, turkish).
nation_to_nationality(turkmenistan, turkmen).
nation_to_nationality(ukraine, ukranian).
nation_to_nationality(the_united_arab_emirates, emirati).
nation_to_nationality(the_united_states, american).
nation_to_nationality(uruguay, uruguayan).
nation_to_nationality(vietnam, vietnamese).
nation_to_nationality(wales, welsh).
nation_to_nationality(zambia, zambian).
nation_to_nationality(zimbabwe, zimbabwean).
