is_open(far_east_pizza).
is_open(la_cuisine_cafe).
is_open(cafe_max_richardson).
is_open(ten50_bbq).
is_open(abu_omar_halal).
is_open(texas_smokehouse_barbque).
is_open(sweet_donuts).
is_open(subway).
is_open(orchard_at_the_office).
is_open(andalous_mediterranean_buffet).
is_open(buffet_at_international_buddhist_progress_society).
is_open(the_house_cafe).
is_open(water_drop_teahouse).
is_open(four_bullets_brewery).
is_open(big_d_kona_ice).
is_open(arapaho_deli).
is_open(eiland_coffee_roasters).
is_open(new_york_eats).
is_open(urban_eatz).
is_open(sakhuu_thai).
is_open(yoshi_shabu_shabu).
is_open(bawarchi_biryanis).
is_open(the_wingd_nut).
is_open(tiffs_treats).
is_open(sweet_mix_desserts).
is_open(menas_texmex_grill_cantina).
is_open(yumilicious).
is_open(potbelly_sandwich_shop).
is_open(starbucks).
is_open(burger_king).
is_open(russos_coal_fired_italian_kitchen).
is_open(jersey_mikes_subs).
is_open(seven_eleven).
is_open(twisted_root_burger__richardson).
is_open(panera_bread).
is_open(chipotle_mexican_grill).
is_open(jimmy_johns).
is_open(velvet_taco_richardson).
is_open(chickfila).
is_open(mcdonalds).
is_open(seven_eleven).
is_open(dimassis_mediterranean_buffet).
is_open(zoes_kitchen).
is_open(the_great_outdoors_sub_shop).
is_open(boots_and_brix).
is_open(tapioca_house).
is_open(taco_cabana).
is_open(first_watch).
is_open(genroku_sushi__grill).
is_open(below_40_fresh_kitchen).
is_open(mumtaz_indian_restaurant).
is_open(aahar_indian_restaurant).
is_open(i_fratelli_pizza_richardson).
is_open(paris_donuts).
is_open(sichuan_king).
is_open(canton_chinese_restaurant).
is_open(which_wich_superior_sandwiches).
is_open(kolache_factory).
is_open(freshii).
is_open(freebirds_world_burrito).
is_open(spin_pizza).
is_open(smoothie_factory).
is_open(fox__hound).
is_open(the_pie_pop_company).
is_open(maru_ramen).
is_open(smoothie_king).
is_open(snuffers).
is_open(asian_mint).
is_open(torchys_tacos).
is_open(snappy_salads).
is_open(taco_ocho).
is_open(nothing_bundt_cakes).
is_open(pho_que_huong).
is_open(teriyaki_sensei).
is_open(tofu_factory_korean_cuisine).
is_open(first_watch).
is_open(tkk_fried_chicken).
is_open(kung_fu_tea).
is_open(jeng_chi_restaurant).
is_open(eightyfivec_bakery_cafe).
is_open(java_land_coffee_haus).
is_open(royal_sichuan).
is_open(international_bakery__sandwich_bar).
is_open(burning_rice).
is_open(pho_corner).
is_open(wendys).
is_open(good_fortune_supermarket).
is_open(bennys_bagels).
is_open(palapas_seafood_bar).
is_open(golden_chick).
is_open(cafe_brazil).
is_open(masala_twist).
is_open(pho_ok).
is_open(sushi_sake).
is_open(olive_burger__richardson).
is_open(spice_n_rice_indian_cuisine).
is_open(mein_cuisine).
is_open(taiwan_cafe).
is_open(vila_brazil_steak_house).
is_open(dominos_pizza).
is_open(jack_in_the_box).
is_open(pho_truong).
is_open(custer_wok).
is_open(ali_baba_mediterranean_grill).
is_open(hometown_cafe).
is_open(dickeys_barbecue_pit).
is_open(tongue_in_cheek_ice_cream).
is_open(taco_bell).
is_open(chien_garden).
is_open(albaghdady_bakery).
is_open(seven_eleven).
is_open(lohas_teriyaki).
is_open(buy_low_food_mart__beer).
is_open(tineo_peruvian_cafe).
is_open(pinedas_mexican_cuisine).
is_open(burger_island).
is_open(cajun_corner).
is_open(anatolia_mart).
is_open(lonestar_grill__sports_cafe).
is_open(tacos_y_mas).
is_open(dominos_pizza).
is_open(oriental_express).
is_open(kebabnkurry).
is_open(spring_creek_barbeque).
is_open(salvadorian_cuisine).
is_open(kasra_persian_restaurant).
is_open(dollar_general_store).
is_open(austin_avenue_grill__sports_bar).
is_open(la_casita_bakeshop).
is_open(los_merla_bakery).
is_open(zaks_donuts).
is_open(trouvi_cookie_company).
is_open(cocina_de_mi_casa).
is_open(amigos_restaurant).
is_open(alon).
is_open(holy_frijoles).
is_open(pho_long_noodle_and_grill).
is_open(hat_creek_burger_company).
is_open(the_line).
is_open(meat_maniac).
is_open(creamy_doughnuts).
is_open(grand_cafe).
is_open(ken_japanese_bistro).
is_open(afrah_restaurant).
is_open(vroom_vroom_valero).
is_open(ziggys_tavern).
is_open(arbys).
is_open(fish_shack).
is_open(tavern_on_main_street).
is_open(krab_kingz_7).
is_open(habibi_cafe).
is_open(jasmine_cafe__hookah_lounge).
is_open(dallas_king_daddy_ice).
is_open(joy_donuts).
is_open(indo_pak_super_market).
is_open(indo_pak_cafe).
is_open(medina_moroccan_and_mediterranean_fusion).
is_open(murphys_deli).
is_open(yummy_burgers__bbq).
is_open(isabellys_sweet_treats).
is_open(first_chinese_bbq).
is_open(boba_latte).
is_open(m2m_bakery).
is_open(albaghdady).
is_open(lockwood_distilling).
is_open(communion_neighborhood_cooperative).
is_open(dels_charcoal_burgers).
is_open(subway).
is_open(sultan_caf).
is_open(new_world_realty).
is_open(fratello_halal_pizza__grill).
is_open(chameli).
is_open(kings_noodle).
is_open(wound_up_cafe).
is_open(creamy_taste_of_heaven).
is_open(sweetstop).
is_open(smoothie_factory).
is_open(pho_tay_do).
is_open(monkey_king_noodle_company).
is_open(first_emperor_chinese_restaurant).
is_open(la_burger).
is_open(bulldog_katsu).
is_open(jamaica_cabana_restaurant).
is_open(marias_bakery).
is_open(gopal_vegetarian_restaurant).
is_open(burger_street).
is_open(al_basha_mediterranean_restaurant).
is_open(quiktrip).
is_open(masami).
is_open(starbucks).
is_open(mcdonalds).
is_open(fish_n_tails_oyster_bar).
is_open(kirin_court_chinese_restaurant).
is_open(mmch_richardson).
is_open(stephanies_kitchen).
is_open(krispy_kreme).
is_open(richardson_beer__wine).
is_open(pizza_hut).
is_open(onetwothree_street_food).
is_open(royal_sweets__fast_food).
is_open(subway).
is_open(subway).
is_open(addis_abeba_ethiopian_restaurant).
is_open(abocas_italian_grill).
is_open(industrial_pizza__brew).
is_open(fusion_vibes_kitchen__bar).
is_open(eileens_pralines).
is_open(the_chefs_cuisine).
is_open(jababae_food_truck).
is_open(mcdonalds).
is_open(pho_bac_restaurant).
is_open(chiloso_mexican_bistro__richardson).
is_open(cafe_cali).
is_open(bikaner_sweets).
is_open(hot_breads).
is_open(one_hummus).
is_open(victor_hugos).
is_open(vegvana).
is_open(little_caesars_pizza).
is_open(porta_di_roma).
is_open(bangkok_at_beltline).
is_open(parks_donuts).
is_open(dos_charros_restaurant).
is_open(glory_chinese_restaurant).
is_open(olive_oils_pizzeria).
is_open(gong_cha).
is_open(fuzzys_taco_shop).
is_open(i_love_u_alatte).
is_open(sweet_daze_dessert_bar).
is_open(smoothie_king).
is_open(alamo_drafthouse_cinema_richardson).
is_open(applebees_grill__bar).
is_open(jimmy_johns).
is_open(cake_carousel).
is_open(cinnaholic).
is_open(flaming_buffet).
is_open(haystack_burgers__barley).
is_open(rickys_hot_chicken).
is_open(cream_and_crepes_cafe).
is_open(guitars__growlers).
is_open(hoki_poki).
is_open(ding_tea__richardson).
is_open(wendys).
is_open(mezza_cafe).
is_open(tasty_tails).
is_open(campbell_donuts).
is_open(woody_bs_mesquite_bbq).
is_open(india_bazaar).
is_open(cafe_bleu).
is_open(docs_food_store).
is_open(chocolate_angel_cafe__tea_room).
is_open(pho_pasteur).
is_open(el_pollo_loco).
is_open(chipotle_mexican_grill).
is_open(golden_joy_bbq).
is_open(cvs_pharmacy).
is_open(thai_asian_fusion_cafe).
is_open(firehouse_subs).
is_open(sharetea).
is_open(quiznos).
is_open(waffle_olicious).
is_open(aldi).
is_open(natural_grocers).
is_open(four_season_farmers_market).
is_open(raising_canes_chicken_fingers).
is_open(bliss_street_bakery).
is_open(whataburger).
is_open(bigdash_ice_cream__pastries).
is_open(mcdonalds).
is_open(sigels).
is_open(zaxbys_chicken_fingers__buffalo_wings).
is_open(sonic_drivein).
is_open(pizza_americana).
is_open(flaming_skewer).
is_open(braums_ice_cream__dairy_stores).
is_open(panda_express).
is_open(danang_souphouse).
is_open(gnc).
is_open(papa_johns_pizza).
is_open(walgreens).
is_open(pizza_hut).
is_open(long_john_silvers).
is_open(pappas_catering).
is_open(pappasitos_cantina).
is_open(taco_bell).
is_open(wingstop).
is_open(tom_thumb_food__pharmacy).
is_open(roccos_italian_caf).
is_open(meteor_hamburgers).
is_open(kroger_food_stores).
is_open(neighbors_food_n_brews).
is_open(pappadeaux_seafood_kitchen).
is_open(d__s_food_mart).
is_open(milano_halal_pizza).
is_open(tjs_dawg_house).
is_open(the_china_express).
is_open(the_wine_authority).
is_open(chickfila).
is_open(zdar_market).
is_open(el_patron_tacos_y_tortas).
is_open(subway).
is_open(baskinrobbins).
is_open(bilad_restaurant__bakery).
is_open(tuscany_italian_bistro).
is_open(albidel_restaurant__bakery).
is_open(honey_donuts).
is_open(saigon_noodle__steak_house).
is_open(mantra_leaf_cafe).
is_open(saigon_block).
is_open(chase_place).
is_open(sababa_mediterranean_cuisine).
is_open(sonic_drivein).
is_open(free_play_arcade).
is_open(wizards_sports_cafe).
is_open(saras_market__bakery).
is_open(s_grill).
is_open(seven_eleven).
is_open(owens_country_sausage).
is_open(kfc).
is_open(chili_gordos_mexican_cafe).
is_open(mcdonalds).
is_open(bunkies_doughnuts).
is_open(dos_arroyos_comida_casera).
is_open(sweet_firefly).
is_open(magic_cup).
is_open(feng_cha_teahouse).
is_open(the_fifth_fireside_patio_and_bar).
is_open(dos_arroyos_comida_casera).
is_open(starbucks).
is_open(cvs_pharmacy).
is_open(al_nimer_roastery).
is_open(shadys_burger_joint).
is_open(sopranos_pizza__subs).
is_open(starbucks).
is_open(waffle_house).
is_open(jack_in_the_box).
is_open(plant_b).
is_open(omg_tacos).
is_open(dog_haus_biergarten).
is_open(walgreens).
is_open(quiktrip).
is_open(shipley_donuts).
is_open(cicis).
is_open(latinos_bakery).
is_open(wendys).
is_open(texadelphia).
is_open(pokeworks).
is_open(popbar).
is_open(xin_xian).
is_open(new_china).
is_open(the_halal_guys).
is_open(wingstop).
is_open(la_paloma).
is_open(sonic_drivein).
is_open(bleachers_sports_grill).
is_open(fish_n_tails_oyster_bar).
is_open(tantuni_mediterranean_grill).
is_open(texaco_garland).
is_open(taqueria_garcias).
is_open(davids_meat_market).
is_open(egg_roll_cafe).
is_open(cvs_pharmacy).
is_open(judys_cafe).
is_open(chilis).
is_open(desperados_mexican_restaurant_dos).
is_open(picngo).
is_open(morning_donuts).
is_open(caprissi_pizza__pasta).
is_open(jasons_deli).
is_open(taqueria_chimalhuacan).
is_open(taco_bueno).
is_open(sweet_shoppe_dfw).
is_open(subway_restaurants).
is_open(dominos_pizza).
is_open(no_1_plus_chicken__richardson).
is_open(gonzos_cocina_mexican_grill).
is_open(ez_shop).
is_open(lemma_coffee_roasters).
is_open(fiesta_mart).
is_open(the_crab_shed).
is_open(dominos_pizza).
is_open(cvs_pharmacy).
is_open(indulgent_treats).
is_open(donut_depot).
is_open(exxon).
is_open(joy_kitchen).
is_open(spring_valley_mart).
is_open(subway).
is_open(lees_sandwiches).
is_open(mi_casita_taqueria).
is_open(jack_in_the_box).
is_open(student_union_dining_hall).
is_open(dashin_grocery__4).
is_open(frutazo_juice_bar__fruteria).
is_open(nanas_country_citchen__catering).
is_open(hot_crab).
is_open(sf_supermarket).
is_open(m__v_quan).
is_open(cha_bong_1).
is_open(banh_mi_1).
is_open(chao_vit_thanh_da).
is_open(sieu_thi_thuan_phat).
is_open(saigon_quan).
is_open(de_nhat_kho_bo).
is_open(noodlelicious).
is_open(seven_eleven).
is_open(hu_tieu_my_tho_restaurant).
is_open(quoc_huong_restaurant).
is_open(panda_express).
is_open(moes_southwest_grill).
is_open(ihop).
is_open(bone_daddys).
is_open(art_bakery).
is_open(saigon_cha_lua).
is_open(asian_buffet).
is_open(nam_hua_vietnamese_cusine).
is_open(bbq_king_restaurant).
is_open(cvs_pharmacy).
is_open(subway).
is_open(starbucks).
is_open(tasty_egg_roll).
is_open(taqueria_garcias).
is_open(boba_heaven).
is_open(subway).
is_open(razzoos_cajun_cafe).
is_open(new_texas_king_zabiha_halal_meat_market).
is_open(roma_palace).
is_open(subzi_mandi).
is_open(darrens_american_grill).
is_open(marcos_pizza).
is_open(chickfila).
is_open(banh_cuon_thang_long).
is_open(seor_chachote_cantina__grill).
is_open(besas_italian_restaurant).
is_open(frankies_mexican_cuisine).
is_open(frankies_place).
is_open(einstein_bros_bagels).
is_open(las_flamas_mexican_kitchen).
is_open(tom_thumb_food__pharmacy).
is_open(new_orleans).
is_open(habesha_ethiopian_coffee).
is_open(ding_tea_garland).
is_open(papa_murphys).
is_open(starbucks).
is_open(tom_yum_thai).
is_open(studio_movie_grill).
is_open(modern_market_eatery).
is_open(luna_grill).
is_open(pei_wei).
is_open(smashburger).
is_open(wendys).
is_open(la_michoacana_meat_market).
is_open(tonys_mexican_cocina).
is_open(smashburger).
is_open(ihop).
is_open(whole_foods_market_city_line).
is_open(sonic_drivein).
is_open(piada_italian_street_food).
is_open(cvs_pharmacy).
is_open(fish_city_grill).
is_open(pho_is_for_lovers).
is_open(super_chix).
is_open(tri_tip_grill).
is_open(grizzly_burger_house).
is_open(burgerim).
is_open(good_union_urban_bbq).
is_open(shuck_n_jive).
is_open(jcs_burger_house).
is_open(donut_palace).
is_open(american_tap_room).
is_open(dangki_fusion).
is_open(fat_straws).
is_open(fernandos_mexican_cuisine).
is_open(walmart_supercenter).
is_open(edoko_sushi__robata).
is_open(sonny_bryans_smokehouse__richardson).
is_open(jaspers_richardson).
is_open(northside_drafthouse__eatery).
is_open(chard_southeast_asian_kitchen).
is_open(panda_express).
is_open(red_mango).
is_open(nestle_toll_house_cafe_by_chip).
is_open(mooyah_burgers_fries__shakes).
is_open(tricky_fish).
is_open(coolgreens).
is_open(ediths_neighborhood_bistro).
is_open(jimmy_johns).
is_open(panda_express).
is_open(delish_bubble_tea).
is_open(pinto_urban_thai_diner).
is_open(chopped_halal_grill).
is_open(dipped).
is_open(starbucks).
is_open(seven_eleven).
is_open(braums_ice_cream_and_dairy_store).
is_open(el_charritos_taqueria).
is_open(world_food_warehouse).
is_open(hong_kong_bakery).
is_open(walnut_food_mart).
is_open(tamalera_nuevo_len).
is_open(korys_deli).
is_open(dennys).
is_open(hong_kong_che).
is_open(la_me).
is_open(doa_maria).
is_open(dire_dawa_cafe__restaurant).
is_open(hong_kong_market).
is_open(mustang_softball_concessions).
is_open(golden_chick).
is_open(sprouts_farmers_market).
is_open(bistro_b).
is_open(dvegan).
is_open(papa_johns_pizza).
is_open(b__p_snacks).
is_open(tx_nutrition).
is_open(golden_crown).
is_open(olive_tree_specialty_foods).
is_open(shahrzad_mediterranean_market__grill).
is_open(pho_95).
is_open(ice_house_beverages).
is_open(louis_pizza).
is_open(twenty_fourhour_pizza).
is_open(tuyet_tofu).
is_open(i_love_donuts).
is_open(albertsons).
is_open(the_string_bean).
is_open(subway).
is_open(the_crab_station__dallas).
is_open(natural_health_shop).
is_open(lucky_bamboo_kitchen).
is_open(gojo_ethiopian_restaurant).
is_open(euro_delicatessen).
is_open(the_brasa_bar__grill).
is_open(tom_thumb).
is_open(griffs_hamburgers).
is_open(masala_wok).
is_open(akaya_sushi_izakaya__ramen).
is_open(papa_murphys).
is_open(wingstop).
is_open(lola_tamales__bakery).
is_open(monta_ramen).
is_open(cafe_gecko).
is_open(sugarless_delite).
is_open(la_madeleine_french_bakery__cafe).
is_open(kroger).
is_open(milk_and_honey).
is_open(starbucks).
is_open(feng_cha__garland).
is_open(starbucks).
is_open(mama_delucas).
is_open(fish__fizz).
is_open(cafe_amore).
is_open(collin_ridge_deli_shop).
is_open(cappuccino_italian_bistro).
is_open(long_time_ago).
is_open(subway).
is_open(star_food_mart).
is_open(donut).
is_open(burger_island).
is_open(subway).
is_open(shuri).
is_open(starbucks).
is_open(pei_wei).
is_open(palios_pizza_cafe__richardson).
is_open(einstein_bros_bagels).
is_open(taqueria_candelaria).
is_open(brizo).
is_open(homebrew_headquarters_inc).
is_open(taqueria_la_candelaria).
is_open(pollo_campero).
is_open(sweet_frog_premium_frozen_yogurt).
is_open(rodeo_goat).
is_open(mi_cocina).
is_open(wingbucket).
is_open(ino_japanese_restaurant).
is_open(bambu_asian_cuisine).
is_open(whataburger).
is_open(monster_yogurt).
is_open(reverie_bakeshop).
is_open(qdoba_mexican_eats).
is_open(little_greek__richardson).
is_open(jersey_mikes_subs).
is_open(jalapeno_mexican_grill).
is_open(tom_thumb).
is_open(walmart_supercenter).
is_open(flying_fish).
is_open(saltgrass_steak_house).
is_open(starbucks).
is_open(masons_cafe).
is_open(walgreens).
is_open(mcdonalds).
is_open(imperial_cuisine).
is_open(pizza_hut).
is_open(tacos_el_vale).
is_open(jcs_burger_bar).
is_open(jasons_deli).
is_open(richardson_farmers_market).
is_open(high_priestess_tea_company).
is_open(bund_wok_plano).
is_open(thai_soon_restaurant).
is_open(tacos_y_mas).
is_open(golden_star_donuts).
is_open(mooyah_burgers_fries__shakes).
is_open(la_michoacana_meat_market).
is_open(the_popcorn_shack).
is_open(campisis_restaurant__coit__campbell).
is_open(curry_bliss).
is_open(dunkin).
is_open(baskinrobbins).
is_open(subway).
is_open(mooya_burger).
is_open(salata).
is_open(gnc).
is_open(dickeys_barbecue_pit).
is_open(angel_chicken_kitchen).
is_open(big_shucks_oyster_bar).
is_open(cerveceria_el_rancho).
is_open(dairy_queen).
is_open(chickfila).
is_open(raising_canes_chicken_fingers).
is_open(little_caesars_pizza).
is_open(texas).
is_open(marrosso_cafe).
is_open(captain_daves_seafood_market).
is_open(quiktrip).
is_open(sweetwaters_coffee__tea_shire_blvd).
is_open(rockfish_seafood_grill).
is_open(shared_table_coffee).
is_open(starbucks).
is_open(shopngo).
is_open(la_picosa).
is_open(elotes_fanny).
is_open(great_wall).
is_open(great_wall_super_buffet).
is_open(chipotle_mexican_grill).
is_open(grocery_services_north).
is_open(cvs_pharmacy).
is_open(hippo).
is_open(jack_in_the_box).
is_open(liberty_burger__richardson).
is_open(walgreens).
is_open(corner_bakery_cafe).
is_open(plano_beverage).
is_open(alma_liquor__market).
is_open(cafe_619).
is_open(deep_cuts).
is_open(anayas_seafood_scratch_kitchen).
is_open(ye_shire_tavern).
is_open(chilis).
is_open(kosher_palate).
is_open(popeyes_louisiana_kitchen).
is_open(cindis_ny_deli__restaurant).
is_open(johns_cafe).
is_open(mannys_uptown_texmex).
is_open(racetrac).
is_open(sushi_rock).
is_open(m_t_a_shaved_ice).
is_open(lovers_egg_roll).
is_open(mcalisters_deli).
is_open(thais_thumbz).
is_open(donut_palace).
is_open(lima_taverna).
is_open(southern_recipes_grill).
is_open(sushi_go).
is_open(roman_cucina).
is_open(pizza_hut).
is_open(love_and_war_in_texas).
is_open(apollonias).
is_open(silver_fox_steakhouse).
is_open(jaimes_donuts).
is_open(gnc).
is_open(fino_restaurant__catering).
is_open(smoothie_factory).
is_open(kroger).
is_open(quiktrip).
is_open(olive_garden_italian_restaurant).
is_open(the_urban_grill).
is_open(jersey_mikes_subs).
is_open(jersey_mikes_subs).
is_open(total_wine__more).
is_open(carmines_pizzeria).
is_open(jupiter_china).
is_open(seven_eleven).
is_open(tetco).
is_open(mcdonalds).
is_open(cvs_pharmacy).
is_open(seven_eleven).
is_open(chinos_tacos).
is_open(pizza_patrn).
is_open(tandoori_pizza).
is_open(hot_pancakes).
is_open(hooters).
is_open(starbucks).
is_open(hooties_burger_bar).
is_open(mr_wongs_chicken__rice).
is_open(jack_in_the_box).
is_open(taqueria_y_restaurante_el_paisano).
is_open(cuquitas_restaurant).
is_open(chevron_mart).
is_open(la_salsa_verde_taqueria).
is_open(donuts).
is_open(simons_sushi).
is_open(el_fenix).
is_open(pho_s_cowboys).
is_open(chocolate_angel_cafe__tea_room__high_street).
is_open(phuong_nam_restaurant).
is_open(kezira_cafe).
is_open(noodle_wave).
is_open(burger_king).
is_open(fiesta_mart).
is_open(taco_bueno).
is_open(shishkabobs_cafe).
is_open(pho_ca_dao).
is_open(jack_in_the_box).
is_open(my_canh_chinese_restaurant).
is_open(parripollo_country).
is_open(pollo_regio).
is_open(hiep_phong_bbq).
is_open(baleadas_by_lilis).
is_open(nunos_tacos__vegmex_grill).
is_open(paleteria_san_marcos).
is_open(q_w_b).
is_open(cicis).
is_open(circle_k).
is_open(highland_springs).
is_open(churchs_chicken).
is_open(chu_chu_grocery_spices__catering).
is_open(burger_king).
is_open(jupiter_liquor).
is_open(kim_ninh_bakery).
is_open(chu_chu_grocery).
is_open(woo_mee_ok_korean_bbq).
is_open(popeyes_louisiana_kitchen).
is_open(the_boiling_crab).
is_open(bida_rang_dong).
is_open(ice_vendors).
is_open(el_rancho).
is_open(e__s_grocery).
is_open(charcoal_avenue).
is_open(quick_shop).
is_open(tejano_bbq__more).
is_open(mcdonalds).
is_open(tikka_n_kabab).
is_open(genghis_grill).
is_open(la_paloma_taqueria).
is_open(in_the_mix_bakery).
is_open(burger_king).
is_open(gnc).
is_open(eggroll_express).
is_open(jasons_deli).
is_open(candy_land).
is_open(aldeez_caribbean_restaurant__event_center).
is_open(northpoint_fresh_market_deli).
is_open(ihop).
is_open(southwest_farmers_market).
is_open(corner_food_mart).
is_open(cafe_mouyyad).
is_open(taco_bueno).
is_open(panera_bread).
is_open(c_store_no_11).
is_open(philly_connection).
is_open(taqueria_la_casita).
is_open(waffle_house).
is_open(angels_beverage_center).
is_open(la_poblanita_mexican_bakery).
is_open(master_wok).
is_open(tortilleria_la_nueva_puntada).
is_open(nest_burger).
is_open(schlotzskys).
is_open(kayio).
is_open(outback_steakhouse).
is_open(red_lobster).
is_open(enchiladas_restaurant__catering).
is_open(chipotle_mexican_grill).
is_open(souper_salad).
is_open(guanaquitas).
is_open(wok_express).
is_open(one_stop_food_store).
is_open(olive_garden_italian_restaurant).
is_open(pangea_restaurant__bar).
is_open(saigon_world_bakery).
is_open(garden_restaurant).
is_open(dong_hai_chinese_restaurant).
is_open(pizza_hut).
is_open(sonic_drivein).
is_open(pho_bang_restaurant).
is_open(aqua_fresh_water_store).
is_open(pollo_regio).
is_open(aldi).
is_open(dong_que).
is_open(truong_nguyen_market).
is_open(viet_tofu).
is_open(northcreek_sandwich_shop).
is_open(qq_cafe).
is_open(la_xanh_restaurant).
is_open(daylight_donuts).
is_open(truong_nguyen).
is_open(sharks_fish__chicken).
is_open(taqueria_el_sabroso).
is_open(tokyo_harbor).
is_open(first_chinese_bbq).
is_open(paesanos_cafe).
is_open(i_love_egg_rolls).
is_open(taco_casa).
is_open(circle_k).
is_open(scooters_coffee).
is_open(kazys_gourmet_shop).
is_open(the_sushi_bar).
is_open(banh_trang_tron_dallas).
is_open(kickin_crab).
is_open(villa_monterrey_restaurant).
is_open(golden_chick).
is_open(sayaka_steak__sushi).
is_open(paleteria_super_smash_ice_cream_and_shaved_ice).
is_open(tocotoco_boba_tea).
is_open(bien_xanh).
is_open(bjs_restaurant__brewhouse).
is_open(racetrac).
is_open(pho_21_noodles__grills).
is_open(la_paloma_taqueria).
is_open(cookies_by_design).
is_open(lus_kitchen).
is_open(hu_tieu_nam_vang).
is_open(a_n_s_fina).
is_open(taco_cabana).
is_open(duc_huong_gio_cha).
is_open(ngon_bistro).
is_open(hiep_thai_food_store).
is_open(acn_herbs__eastern_tradition_chinese_herbs).
is_open(big_mamas_chicken__waffles).
is_open(doan_restaurant).
is_open(swadeshi_indian_cuisine).
is_open(sarahs_caf__panini).
is_open(ibex_ethiopian_cuisine_and_bar).
is_open(delicious_deli).
is_open(bos_chicken__seafood).
is_open(ba_le_restaurant__bakery).
is_open(the_dark_chocolate_bakery).
is_open(egg_stand).
is_open(pie_flutin_pastries).
is_open(quoc_bao_bakery).
is_open(pizza_patrn).
is_open(e_z_shop).
is_open(einstein_bros_bagels).
is_open(seven_eleven).
is_open(pizza_patrn).
is_open(fish_n_tails_oyster_bar).
is_open(tasty_asia_restaurant).
is_open(tasty_china).
is_open(grillmasters_meat).
is_open(golden_chick).
is_open(chickfila).
is_open(com_tam_thuan_kieu).
is_open(la_madeleine_french_bakery__cafe).
is_open(sky_rocket_burger).
is_open(hot_and_creamy_donuts).
is_open(raising_canes_chicken_fingers).
is_open(central_market).
is_open(whataburger).
is_open(kim_lan_food_to_go).
is_open(kumars__plano).
is_open(hu_tieu_my_tho).
is_open(trak_10).
is_open(quiktrip).
is_open(tai_zong_si_chuan).
is_open(taco_express).
is_open(jack_in_the_box).
is_open(los_compadres_taqueria).
is_open(jack_in_the_box).
is_open(mcdonalds).
is_open(mcdonalds).
is_open(mcdonalds).
is_open(taco_bell).
is_open(walmart_supercenter).
is_open(saigon_deli).
is_open(seven_eleven).
is_open(la_super_paleteria).
is_open(wuden_chopsticks).
is_open(potbelly_sandwich_shop).
is_open(boston_market).
is_open(desta_ethiopian_restaurant).
is_open(kfc).
is_open(stone_pit_wings).
is_open(quiktrip).
is_open(fusion_sichuan_cuisine).
is_open(el_pollo_loco).
is_open(daddy_bobs_catfish).
is_open(urban_rio_cantina__grill).
is_open(long_john_silvers).
is_open(grandys).
is_open(jgs_old_fashioned_hamburgers).
is_open(fish_shack).
is_open(on_the_border_mexican_grill__cantina).
is_open(el_rancho_supermercado).
is_open(abugeda_grocery).
is_open(tacqueria_nuevo_len).
is_open(ostioneria_7_mares).
is_open(churchs_chicken).
is_open(sushi_ichiban).
is_open(retro_taco).
is_open(williams_chicken).
is_open(chipotle_mexican_grill).
is_open(starbucks).
is_open(normas_cafe).
is_open(arbys).
is_open(subway).
is_open(vivi_bubble_tea).
is_open(sakura_chinese_bbq).
is_open(taco_cabana).
is_open(dantes_italian_eatery).
is_open(smoothie_king).
is_open(seven_eleven).
is_open(wus_super_bowl).
is_open(starbucks).
is_open(city_cafe__bakery).
is_open(captain_ds).
is_open(starbucks).
is_open(mcdonalds).
is_open(whataburger).
is_open(subway).
is_open(dominos_pizza).
is_open(mcdonalds).
is_open(outback_steakhouse).
is_open(mcdonalds).
is_open(eddys_pizza_restaurant).
is_open(uni_sushi).
is_open(pink_coffee).
is_open(kegs__barrels).
is_open(hub_streat).
is_open(georgias_farmers_market).
is_open(garland_cafe).
is_open(red_seven_convenience_store).
is_open(morning_donuts).
is_open(ruang_thai).
is_open(urban_nutrition_lounge).
is_open(gogiya).
is_open(mcdonalds).
is_open(maries_kitchen).
is_open(popeyes_louisiana_kitchen).
is_open(taco_bell).
is_open(urban_crust).
is_open(the_fillmore_pub).
is_open(cvs_pharmacy).
is_open(burger_bueno).
is_open(cvs_pharmacy).
is_open(the_boiling_crab).
is_open(ye_ole_butcher_shop).
is_open(cotton_candy_donuts).
is_open(better_than_sex__a_dessert_restaurant_plano).
is_open(dickeys_barbecue_pit).
is_open(fourteeneighteencoffee_house).
is_open(yegna_juice_bar).
is_open(gracious_baking).
is_open(sini_coffee_lounge).
is_open(taco_bell).
is_open(viet_quan).
is_open(wingstop).
is_open(lockhart_smokehouse).
is_open(zalat_pizza).
is_open(the_gelato_cone).
is_open(taco_chaco_4).
is_open(rosas_caf__tortilla_factory).
is_open(fcking_good_pizza).
is_open(ebesu_robatasushi).
is_open(trompo_taqueria__burgers).
is_open(seven_eleven).
is_open(daylight_donuts).
is_open(subway).
is_open(xo_coffee_company).
is_open(pho_95_restaurant).
is_open(vickery_park_plano).
is_open(sams_club).
is_open(jorgs_cafe_vienna).
is_open(kfc).
is_open(sushi_town).
is_open(apple_spice).
is_open(kfc).
is_open(pizza).
is_open(sarah_emilys_home_baked_cookies).
is_open(freds_downtown_philly).
is_open(primo_brothers_pizza).
is_open(sweetbasil_thai_kitchen__garland).
is_open(hawaiian_bros).
is_open(wannaeat_seafood).
is_open(wingstop).
is_open(sicilianos_a_taste_of_italy).
is_open(seven_eleven).
is_open(bernards_gourmet_foods).
is_open(lalibela_ethiopian_restaurant).
is_open(asian_thai_2_go).
is_open(abyssinia_gebya).
is_open(in_the_cut_cafe).
is_open(tlc_vegan_kitchen).
is_open(good_wings).
is_open(meat_point).
is_open(starbucks).
is_open(ricks_old_fashioned_burgers).
is_open(burger_king).
is_open(cafe_biarritz).
is_open(golden_chick).