category(far_east_pizza, pizza).
category(far_east_pizza, pastashops).
category(far_east_pizza, sandwiches).
category(la_cuisine_cafe, cafes).
category(cafe_max_richardson, newamerican).
category(ten50_bbq, bbq).
category(ten50_bbq, tradamerican).
category(abu_omar_halal, halal).
category(abu_omar_halal, mediterranean).
category(abu_omar_halal, foodtrucks).
category(texas_smokehouse_barbque, bbq).
category(sweet_donuts, donuts).
category(subway, sandwiches).
category(orchard_at_the_office, fooddeliveryservices).
category(andalous_mediterranean_buffet, mediterranean).
category(andalous_mediterranean_buffet, halal).
category(andalous_mediterranean_buffet, lebanese).
category(buffet_at_international_buddhist_progress_society, buffets).
category(buffet_at_international_buddhist_progress_society, vegetarian).
category(the_house_cafe, cafes).
category(the_house_cafe, breakfast_brunch).
category(water_drop_teahouse, tea).
category(water_drop_teahouse, vegetarian).
category(four_bullets_brewery, breweries).
category(big_d_kona_ice, shavedice).
category(arapaho_deli, breakfast_brunch).
category(arapaho_deli, tradamerican).
category(arapaho_deli, salad).
category(eiland_coffee_roasters, coffeeroasteries).
category(new_york_eats, mediterranean).
category(new_york_eats, halal).
category(new_york_eats, newamerican).
category(urban_eatz, newamerican).
category(sakhuu_thai, thai).
category(yoshi_shabu_shabu, japanese).
category(yoshi_shabu_shabu, fondue).
category(yoshi_shabu_shabu, hotpot).
category(bawarchi_biryanis, indpak).
category(bawarchi_biryanis, halal).
category(bawarchi_biryanis, kebab).
category(the_wingd_nut, chicken_wings).
category(the_wingd_nut, sportsbars).
category(the_wingd_nut, breakfast_brunch).
category(tiffs_treats, desserts).
category(sweet_mix_desserts, shavedsnow).
category(sweet_mix_desserts, creperies).
category(sweet_mix_desserts, bubbletea).
category(menas_texmex_grill_cantina, tex-mex).
category(menas_texmex_grill_cantina, mexican).
category(yumilicious, desserts).
category(yumilicious, icecream).
category(yumilicious, gelato).
category(potbelly_sandwich_shop, sandwiches).
category(potbelly_sandwich_shop, hotdogs).
category(potbelly_sandwich_shop, salad).
category(starbucks, coffee).
category(burger_king, burgers).
category(burger_king, hotdogs).
category(russos_coal_fired_italian_kitchen, pizza).
category(russos_coal_fired_italian_kitchen, italian).
category(jersey_mikes_subs, sandwiches).
category(jersey_mikes_subs, delis).
category(jersey_mikes_subs, hotdogs).
category(seven_eleven, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, coffee).
category(twisted_root_burger__richardson, burgers).
category(twisted_root_burger__richardson, divebars).
category(twisted_root_burger__richardson, tradamerican).
category(panera_bread, sandwiches).
category(panera_bread, salad).
category(panera_bread, soup).
category(chipotle_mexican_grill, hotdogs).
category(chipotle_mexican_grill, mexican).
category(jimmy_johns, sandwiches).
category(jimmy_johns, delis).
category(jimmy_johns, hotdogs).
category(velvet_taco_richardson, tacos).
category(velvet_taco_richardson, newamerican).
category(velvet_taco_richardson, vegetarian).
category(chickfila, hotdogs).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(seven_eleven, coffee).
category(seven_eleven, convenience).
category(dimassis_mediterranean_buffet, mediterranean).
category(dimassis_mediterranean_buffet, mideastern).
category(dimassis_mediterranean_buffet, buffets).
category(zoes_kitchen, mediterranean).
category(zoes_kitchen, greek).
category(zoes_kitchen, sandwiches).
category(the_great_outdoors_sub_shop, sandwiches).
category(the_great_outdoors_sub_shop, salad).
category(the_great_outdoors_sub_shop, icecream).
category(boots_and_brix, newamerican).
category(tapioca_house, coffee).
category(tapioca_house, bubbletea).
category(tapioca_house, taiwanese).
category(taco_cabana, mexican).
category(first_watch, tradamerican).
category(first_watch, breakfast_brunch).
category(first_watch, cafes).
category(genroku_sushi__grill, sushi).
category(genroku_sushi__grill, japanese).
category(genroku_sushi__grill, chinese).
category(below_40_fresh_kitchen, asianfusion).
category(below_40_fresh_kitchen, poke).
category(mumtaz_indian_restaurant, indpak).
category(aahar_indian_restaurant, indpak).
category(i_fratelli_pizza_richardson, pizza).
category(paris_donuts, donuts).
category(sichuan_king, szechuan).
category(canton_chinese_restaurant, chinese).
category(which_wich_superior_sandwiches, sandwiches).
category(kolache_factory, bakeries).
category(kolache_factory, breakfast_brunch).
category(kolache_factory, coffee).
category(freshii, salad).
category(freshii, juicebars).
category(freshii, vegetarian).
category(freebirds_world_burrito, mexican).
category(freebirds_world_burrito, tex-mex).
category(spin_pizza, pizza).
category(spin_pizza, salad).
category(spin_pizza, sandwiches).
category(smoothie_factory, juicebars).
category(fox__hound, sportsbars).
category(fox__hound, burgers).
category(fox__hound, tradamerican).
category(the_pie_pop_company, bakeries).
category(maru_ramen, ramen).
category(maru_ramen, asianfusion).
category(maru_ramen, noodles).
category(smoothie_king, healthmarkets).
category(smoothie_king, juicebars).
category(snuffers, burgers).
category(snuffers, tradamerican).
category(snuffers, bars).
category(asian_mint, thai).
category(asian_mint, asianfusion).
category(torchys_tacos, tex-mex).
category(torchys_tacos, tacos).
category(snappy_salads, salad).
category(snappy_salads, wraps).
category(taco_ocho, mexican).
category(taco_ocho, breakfast_brunch).
category(nothing_bundt_cakes, bakeries).
category(nothing_bundt_cakes, desserts).
category(nothing_bundt_cakes, cupcakes).
category(pho_que_huong, vietnamese).
category(teriyaki_sensei, japanese).
category(tofu_factory_korean_cuisine, korean).
category(tofu_factory_korean_cuisine, bbq).
category(first_watch, breakfast_brunch).
category(first_watch, cafes).
category(first_watch, tradamerican).
category(tkk_fried_chicken, chickenshop).
category(tkk_fried_chicken, taiwanese).
category(tkk_fried_chicken, sandwiches).
category(kung_fu_tea, bubbletea).
category(kung_fu_tea, coffee).
category(kung_fu_tea, juicebars).
category(jeng_chi_restaurant, bakeries).
category(jeng_chi_restaurant, chinese).
category(jeng_chi_restaurant, cocktailbars).
category(eightyfivec_bakery_cafe, bakeries).
category(eightyfivec_bakery_cafe, coffee).
category(eightyfivec_bakery_cafe, cakeshop).
category(java_land_coffee_haus, coffee).
category(java_land_coffee_haus, chicken_wings).
category(java_land_coffee_haus, waffles).
category(royal_sichuan, chinese).
category(international_bakery__sandwich_bar, bakeries).
category(international_bakery__sandwich_bar, sandwiches).
category(burning_rice, korean).
category(burning_rice, bbq).
category(pho_corner, vietnamese).
category(pho_corner, noodles).
category(pho_corner, seafood).
category(wendys, hotdogs).
category(wendys, burgers).
category(good_fortune_supermarket, grocery).
category(bennys_bagels, bagels).
category(bennys_bagels, breakfast_brunch).
category(palapas_seafood_bar, bars).
category(palapas_seafood_bar, seafood).
category(palapas_seafood_bar, mexican).
category(golden_chick, hotdogs).
category(cafe_brazil, breakfast_brunch).
category(cafe_brazil, coffee).
category(cafe_brazil, tradamerican).
category(masala_twist, indpak).
category(masala_twist, seafood).
category(pho_ok, vietnamese).
category(sushi_sake, japanese).
category(sushi_sake, sushi).
category(olive_burger__richardson, burgers).
category(olive_burger__richardson, halal).
category(olive_burger__richardson, sandwiches).
category(spice_n_rice_indian_cuisine, indpak).
category(spice_n_rice_indian_cuisine, bangladeshi).
category(mein_cuisine, chinese).
category(taiwan_cafe, chinese).
category(taiwan_cafe, noodles).
category(taiwan_cafe, seafood).
category(vila_brazil_steak_house, brazilian).
category(vila_brazil_steak_house, steak).
category(dominos_pizza, pizza).
category(dominos_pizza, chicken_wings).
category(dominos_pizza, sandwiches).
category(jack_in_the_box, burgers).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, tacos).
category(pho_truong, vietnamese).
category(custer_wok, chinese).
category(ali_baba_mediterranean_grill, mediterranean).
category(ali_baba_mediterranean_grill, buffets).
category(ali_baba_mediterranean_grill, salad).
category(hometown_cafe, chinese).
category(hometown_cafe, juicebars).
category(hometown_cafe, seafood).
category(dickeys_barbecue_pit, bbq).
category(dickeys_barbecue_pit, tradamerican).
category(dickeys_barbecue_pit, chicken_wings).
category(tongue_in_cheek_ice_cream, icecream).
category(taco_bell, mexican).
category(taco_bell, hotdogs).
category(chien_garden, chinese).
category(chien_garden, korean).
category(chien_garden, asianfusion).
category(albaghdady_bakery, bakeries).
category(albaghdady_bakery, cafes).
category(seven_eleven, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, coffee).
category(lohas_teriyaki, asianfusion).
category(buy_low_food_mart__beer, beer_and_wine).
category(tineo_peruvian_cafe, peruvian).
category(tineo_peruvian_cafe, bakeries).
category(pinedas_mexican_cuisine, mexican).
category(pinedas_mexican_cuisine, tex-mex).
category(burger_island, burgers).
category(burger_island, sandwiches).
category(cajun_corner, cajun).
category(cajun_corner, seafood).
category(anatolia_mart, turkish).
category(anatolia_mart, grocery).
category(lonestar_grill__sports_cafe, sportsbars).
category(lonestar_grill__sports_cafe, tradamerican).
category(tacos_y_mas, mexican).
category(tacos_y_mas, breakfast_brunch).
category(tacos_y_mas, tex-mex).
category(dominos_pizza, pizza).
category(dominos_pizza, chicken_wings).
category(dominos_pizza, sandwiches).
category(oriental_express, chinese).
category(kebabnkurry, indpak).
category(spring_creek_barbeque, bbq).
category(salvadorian_cuisine, latin).
category(kasra_persian_restaurant, mideastern).
category(kasra_persian_restaurant, persian).
category(kasra_persian_restaurant, afghani).
category(dollar_general_store, convenience).
category(austin_avenue_grill__sports_bar, tradamerican).
category(austin_avenue_grill__sports_bar, sportsbars).
category(la_casita_bakeshop, bakeries).
category(la_casita_bakeshop, customcakes).
category(la_casita_bakeshop, bagels).
category(los_merla_bakery, customcakes).
category(los_merla_bakery, cakeshop).
category(los_merla_bakery, chimneycakes).
category(zaks_donuts, donuts).
category(trouvi_cookie_company, desserts).
category(cocina_de_mi_casa, peruvian).
category(amigos_restaurant, mexican).
category(amigos_restaurant, tex-mex).
category(amigos_restaurant, cocktailbars).
category(alon, servicestations).
category(alon, convenience).
category(holy_frijoles, mexican).
category(holy_frijoles, tex-mex).
category(holy_frijoles, breakfast_brunch).
category(pho_long_noodle_and_grill, vietnamese).
category(pho_long_noodle_and_grill, coffee).
category(pho_long_noodle_and_grill, noodles).
category(hat_creek_burger_company, burgers).
category(hat_creek_burger_company, hotdogs).
category(the_line, pizza).
category(the_line, burgers).
category(the_line, pubs).
category(meat_maniac, gourmet).
category(creamy_doughnuts, donuts).
category(grand_cafe, mideastern).
category(grand_cafe, mediterranean).
category(ken_japanese_bistro, tapasmallplates).
category(ken_japanese_bistro, ramen).
category(ken_japanese_bistro, izakaya).
category(afrah_restaurant, mediterranean).
category(afrah_restaurant, lebanese).
category(vroom_vroom_valero, servicestations).
category(vroom_vroom_valero, convenience).
category(ziggys_tavern, burgers).
category(arbys, hotdogs).
category(arbys, sandwiches).
category(fish_shack, seafood).
category(tavern_on_main_street, newamerican).
category(tavern_on_main_street, pubs).
category(tavern_on_main_street, karaoke).
category(krab_kingz_7, seafood).
category(krab_kingz_7, cajun).
category(habibi_cafe, mideastern).
category(habibi_cafe, hookah_bars).
category(jasmine_cafe__hookah_lounge, hookah_bars).
category(jasmine_cafe__hookah_lounge, mideastern).
category(jasmine_cafe__hookah_lounge, mediterranean).
category(dallas_king_daddy_ice, fooddeliveryservices).
category(joy_donuts, donuts).
category(indo_pak_super_market, grocery).
category(indo_pak_super_market, indpak).
category(indo_pak_super_market, importedfood).
category(indo_pak_cafe, indpak).
category(indo_pak_cafe, pakistani).
category(medina_moroccan_and_mediterranean_fusion, moroccan).
category(medina_moroccan_and_mediterranean_fusion, mediterranean).
category(medina_moroccan_and_mediterranean_fusion, sandwiches).
category(murphys_deli, salad).
category(murphys_deli, sandwiches).
category(murphys_deli, breakfast_brunch).
category(yummy_burgers__bbq, burgers).
category(yummy_burgers__bbq, sandwiches).
category(yummy_burgers__bbq, bbq).
category(isabellys_sweet_treats, bakeries).
category(isabellys_sweet_treats, chocolate).
category(isabellys_sweet_treats, desserts).
category(first_chinese_bbq, chinese).
category(boba_latte, coffee).
category(boba_latte, bubbletea).
category(boba_latte, juicebars).
category(m2m_bakery, cupcakes).
category(m2m_bakery, customcakes).
category(m2m_bakery, bakeries).
category(albaghdady, bakeries).
category(albaghdady, mideastern).
category(lockwood_distilling, distilleries).
category(communion_neighborhood_cooperative, coffee).
category(communion_neighborhood_cooperative, breakfast_brunch).
category(communion_neighborhood_cooperative, tradamerican).
category(dels_charcoal_burgers, burgers).
category(subway, sandwiches).
category(sultan_caf, hookah_bars).
category(sultan_caf, mediterranean).
category(new_world_realty, convenience).
category(fratello_halal_pizza__grill, pizza).
category(fratello_halal_pizza__grill, halal).
category(fratello_halal_pizza__grill, burgers).
category(chameli, indpak).
category(chameli, bangladeshi).
category(kings_noodle, taiwanese).
category(kings_noodle, noodles).
category(wound_up_cafe, foodtrucks).
category(creamy_taste_of_heaven, icecream).
category(creamy_taste_of_heaven, foodtrucks).
category(sweetstop, desserts).
category(sweetstop, bakeries).
category(sweetstop, cupcakes).
category(smoothie_factory, icecream).
category(smoothie_factory, juicebars).
category(pho_tay_do, vietnamese).
category(monkey_king_noodle_company, chinese).
category(first_emperor_chinese_restaurant, chinese).
category(la_burger, burgers).
category(bulldog_katsu, japanese).
category(bulldog_katsu, korean).
category(bulldog_katsu, noodles).
category(jamaica_cabana_restaurant, caribbean).
category(marias_bakery, bakeries).
category(gopal_vegetarian_restaurant, indpak).
category(gopal_vegetarian_restaurant, vegetarian).
category(burger_street, burgers).
category(al_basha_mediterranean_restaurant, greek).
category(quiktrip, servicestations).
category(quiktrip, convenience).
category(quiktrip, hotdogs).
category(masami, japanese).
category(starbucks, coffee).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(fish_n_tails_oyster_bar, seafood).
category(kirin_court_chinese_restaurant, dimsum).
category(kirin_court_chinese_restaurant, seafood).
category(mmch_richardson, bubbletea).
category(stephanies_kitchen, diyfood).
category(krispy_kreme, donuts).
category(krispy_kreme, coffee).
category(richardson_beer__wine, beer_and_wine).
category(pizza_hut, italian).
category(pizza_hut, pizza).
category(pizza_hut, chicken_wings).
category(onetwothree_street_food, burgers).
category(onetwothree_street_food, sandwiches).
category(royal_sweets__fast_food, desserts).
category(royal_sweets__fast_food, indpak).
category(royal_sweets__fast_food, importedfood).
category(subway, sandwiches).
category(subway, sandwiches).
category(addis_abeba_ethiopian_restaurant, ethiopian).
category(abocas_italian_grill, italian).
category(abocas_italian_grill, pizza).
category(abocas_italian_grill, diners).
category(industrial_pizza__brew, pizza).
category(industrial_pizza__brew, salad).
category(fusion_vibes_kitchen__bar, african).
category(fusion_vibes_kitchen__bar, burgers).
category(fusion_vibes_kitchen__bar, chicken_wings).
category(eileens_pralines, desserts).
category(the_chefs_cuisine, fooddeliveryservices).
category(jababae_food_truck, foodtrucks).
category(jababae_food_truck, taiwanese).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(pho_bac_restaurant, vietnamese).
category(chiloso_mexican_bistro__richardson, bars).
category(chiloso_mexican_bistro__richardson, breakfast_brunch).
category(chiloso_mexican_bistro__richardson, mexican).
category(cafe_cali, coffee).
category(bikaner_sweets, desserts).
category(bikaner_sweets, indpak).
category(bikaner_sweets, vegetarian).
category(hot_breads, bakeries).
category(one_hummus, mediterranean).
category(victor_hugos, tradamerican).
category(victor_hugos, cocktailbars).
category(vegvana, indpak).
category(vegvana, vegetarian).
category(little_caesars_pizza, pizza).
category(porta_di_roma, bars).
category(porta_di_roma, cafes).
category(porta_di_roma, italian).
category(bangkok_at_beltline, thai).
category(bangkok_at_beltline, tea).
category(bangkok_at_beltline, asianfusion).
category(parks_donuts, donuts).
category(dos_charros_restaurant, mexican).
category(dos_charros_restaurant, tex-mex).
category(glory_chinese_restaurant, chinese).
category(olive_oils_pizzeria, pizza).
category(gong_cha, bubbletea).
category(fuzzys_taco_shop, tex-mex).
category(i_love_u_alatte, coffee).
category(i_love_u_alatte, sandwiches).
category(i_love_u_alatte, breakfast_brunch).
category(sweet_daze_dessert_bar, desserts).
category(sweet_daze_dessert_bar, icecream).
category(sweet_daze_dessert_bar, bakeries).
category(smoothie_king, juicebars).
category(smoothie_king, healthmarkets).
category(alamo_drafthouse_cinema_richardson, movietheaters).
category(alamo_drafthouse_cinema_richardson, bars).
category(alamo_drafthouse_cinema_richardson, dinnertheater).
category(applebees_grill__bar, tradamerican).
category(applebees_grill__bar, sportsbars).
category(applebees_grill__bar, burgers).
category(jimmy_johns, sandwiches).
category(jimmy_johns, hotdogs).
category(jimmy_johns, delis).
category(cake_carousel, bakeries).
category(cake_carousel, desserts).
category(cake_carousel, cookingclasses).
category(cinnaholic, desserts).
category(cinnaholic, vegan).
category(cinnaholic, bakeries).
category(flaming_buffet, chinese).
category(haystack_burgers__barley, burgers).
category(haystack_burgers__barley, sandwiches).
category(rickys_hot_chicken, chicken_wings).
category(rickys_hot_chicken, chickenshop).
category(rickys_hot_chicken, halal).
category(cream_and_crepes_cafe, desserts).
category(cream_and_crepes_cafe, creperies).
category(cream_and_crepes_cafe, icecream).
category(guitars__growlers, beerbar).
category(guitars__growlers, sandwiches).
category(guitars__growlers, newamerican).
category(hoki_poki, poke).
category(hoki_poki, asianfusion).
category(ding_tea__richardson, coffee).
category(ding_tea__richardson, bubbletea).
category(ding_tea__richardson, juicebars).
category(wendys, burgers).
category(wendys, hotdogs).
category(mezza_cafe, mideastern).
category(tasty_tails, southern).
category(tasty_tails, cajun).
category(tasty_tails, seafood).
category(campbell_donuts, donuts).
category(woody_bs_mesquite_bbq, bbq).
category(india_bazaar, grocery).
category(cafe_bleu, cafes).
category(docs_food_store, convenience).
category(chocolate_angel_cafe__tea_room, chocolate).
category(chocolate_angel_cafe__tea_room, tea).
category(chocolate_angel_cafe__tea_room, cafes).
category(pho_pasteur, vietnamese).
category(el_pollo_loco, hotdogs).
category(el_pollo_loco, mexican).
category(chipotle_mexican_grill, hotdogs).
category(chipotle_mexican_grill, mexican).
category(golden_joy_bbq, dimsum).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(thai_asian_fusion_cafe, thai).
category(thai_asian_fusion_cafe, asianfusion).
category(firehouse_subs, hotdogs).
category(firehouse_subs, delis).
category(firehouse_subs, sandwiches).
category(sharetea, bubbletea).
category(sharetea, coffee).
category(sharetea, juicebars).
category(quiznos, sandwiches).
category(quiznos, delis).
category(waffle_olicious, foodtrucks).
category(waffle_olicious, waffles).
category(aldi, grocery).
category(aldi, markets).
category(aldi, organic_stores).
category(natural_grocers, grocery).
category(natural_grocers, vitaminssupplements).
category(natural_grocers, organic_stores).
category(four_season_farmers_market, farmersmarket).
category(raising_canes_chicken_fingers, hotdogs).
category(bliss_street_bakery, farmersmarket).
category(whataburger, hotdogs).
category(whataburger, burgers).
category(bigdash_ice_cream__pastries, desserts).
category(bigdash_ice_cream__pastries, mideastern).
category(bigdash_ice_cream__pastries, icecream).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(sigels, beer_and_wine).
category(zaxbys_chicken_fingers__buffalo_wings, chicken_wings).
category(zaxbys_chicken_fingers__buffalo_wings, hotdogs).
category(zaxbys_chicken_fingers__buffalo_wings, salad).
category(sonic_drivein, hotdogs).
category(sonic_drivein, burgers).
category(sonic_drivein, icecream).
category(pizza_americana, pizza).
category(pizza_americana, bars).
category(flaming_skewer, pakistani).
category(flaming_skewer, halal).
category(flaming_skewer, salad).
category(braums_ice_cream__dairy_stores, icecream).
category(panda_express, chinese).
category(panda_express, hotdogs).
category(danang_souphouse, vietnamese).
category(gnc, healthmarkets).
category(gnc, vitaminssupplements).
category(papa_johns_pizza, pizza).
category(walgreens, cosmetics).
category(walgreens, drugstores).
category(walgreens, convenience).
category(pizza_hut, pizza).
category(pizza_hut, italian).
category(pizza_hut, chicken_wings).
category(long_john_silvers, hotdogs).
category(long_john_silvers, seafood).
category(pappas_catering, seafood).
category(pappas_catering, tex-mex).
category(pappasitos_cantina, tex-mex).
category(pappasitos_cantina, cajun).
category(pappasitos_cantina, seafood).
category(taco_bell, mexican).
category(taco_bell, hotdogs).
category(wingstop, chicken_wings).
category(tom_thumb_food__pharmacy, bakeries).
category(tom_thumb_food__pharmacy, grocery).
category(tom_thumb_food__pharmacy, beer_and_wine).
category(roccos_italian_caf, italian).
category(roccos_italian_caf, pizza).
category(roccos_italian_caf, sandwiches).
category(meteor_hamburgers, burgers).
category(kroger_food_stores, grocery).
category(neighbors_food_n_brews, convenience).
category(pappadeaux_seafood_kitchen, seafood).
category(pappadeaux_seafood_kitchen, cajun).
category(pappadeaux_seafood_kitchen, cocktailbars).
category(d__s_food_mart, grocery).
category(milano_halal_pizza, halal).
category(milano_halal_pizza, pizza).
category(milano_halal_pizza, desserts).
category(tjs_dawg_house, hotdog).
category(tjs_dawg_house, hotdogs).
category(tjs_dawg_house, foodtrucks).
category(the_china_express, chinese).
category(the_wine_authority, winetastingroom).
category(the_wine_authority, wine_bars).
category(chickfila, hotdogs).
category(zdar_market, mediterranean).
category(zdar_market, mideastern).
category(zdar_market, arabian).
category(el_patron_tacos_y_tortas, mexican).
category(el_patron_tacos_y_tortas, breakfast_brunch).
category(subway, sandwiches).
category(baskinrobbins, icecream).
category(bilad_restaurant__bakery, mediterranean).
category(bilad_restaurant__bakery, bakeries).
category(bilad_restaurant__bakery, mideastern).
category(tuscany_italian_bistro, italian).
category(tuscany_italian_bistro, pizza).
category(tuscany_italian_bistro, seafood).
category(albidel_restaurant__bakery, mideastern).
category(honey_donuts, donuts).
category(honey_donuts, coffee).
category(saigon_noodle__steak_house, vietnamese).
category(saigon_noodle__steak_house, noodles).
category(mantra_leaf_cafe, bubbletea).
category(mantra_leaf_cafe, cafes).
category(mantra_leaf_cafe, shavedsnow).
category(saigon_block, vietnamese).
category(chase_place, bars).
category(chase_place, burgers).
category(chase_place, tradamerican).
category(sababa_mediterranean_cuisine, buffets).
category(sababa_mediterranean_cuisine, mediterranean).
category(sababa_mediterranean_cuisine, kebab).
category(sonic_drivein, burgers).
category(sonic_drivein, hotdogs).
category(sonic_drivein, icecream).
category(free_play_arcade, bars).
category(free_play_arcade, newamerican).
category(free_play_arcade, arcades).
category(wizards_sports_cafe, cafes).
category(wizards_sports_cafe, sportsbars).
category(wizards_sports_cafe, poolhalls).
category(saras_market__bakery, desserts).
category(saras_market__bakery, intlgrocery).
category(saras_market__bakery, butcher).
category(s_grill, mediterranean).
category(s_grill, desserts).
category(s_grill, lebanese).
category(seven_eleven, coffee).
category(seven_eleven, servicestations).
category(seven_eleven, convenience).
category(owens_country_sausage, meats).
category(kfc, hotdogs).
category(kfc, chicken_wings).
category(kfc, chickenshop).
category(chili_gordos_mexican_cafe, mexican).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(bunkies_doughnuts, donuts).
category(dos_arroyos_comida_casera, mexican).
category(dos_arroyos_comida_casera, breakfast_brunch).
category(dos_arroyos_comida_casera, tex-mex).
category(sweet_firefly, icecream).
category(sweet_firefly, shavedice).
category(sweet_firefly, candy).
category(magic_cup, coffee).
category(magic_cup, bubbletea).
category(magic_cup, juicebars).
category(feng_cha_teahouse, desserts).
category(feng_cha_teahouse, bubbletea).
category(feng_cha_teahouse, coffee).
category(the_fifth_fireside_patio_and_bar, newamerican).
category(the_fifth_fireside_patio_and_bar, cocktailbars).
category(the_fifth_fireside_patio_and_bar, breakfast_brunch).
category(dos_arroyos_comida_casera, mexican).
category(starbucks, coffee).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(al_nimer_roastery, coffeeroasteries).
category(al_nimer_roastery, chocolate).
category(al_nimer_roastery, herbsandspices).
category(shadys_burger_joint, burgers).
category(shadys_burger_joint, newamerican).
category(shadys_burger_joint, salad).
category(sopranos_pizza__subs, pizza).
category(starbucks, coffee).
category(waffle_house, diners).
category(waffle_house, breakfast_brunch).
category(waffle_house, tradamerican).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(jack_in_the_box, tacos).
category(plant_b, burgers).
category(plant_b, vegetarian).
category(plant_b, vegan).
category(omg_tacos, asianfusion).
category(omg_tacos, mexican).
category(omg_tacos, tex-mex).
category(dog_haus_biergarten, hotdog).
category(dog_haus_biergarten, burgers).
category(dog_haus_biergarten, beergardens).
category(walgreens, drugstores).
category(walgreens, cosmetics).
category(walgreens, convenience).
category(quiktrip, servicestations).
category(quiktrip, convenience).
category(quiktrip, hotdogs).
category(shipley_donuts, donuts).
category(cicis, pizza).
category(latinos_bakery, bakeries).
category(latinos_bakery, desserts).
category(latinos_bakery, donuts).
category(wendys, hotdogs).
category(wendys, burgers).
category(texadelphia, cheesesteaks).
category(pokeworks, poke).
category(pokeworks, salad).
category(pokeworks, sushi).
category(popbar, icecream).
category(popbar, desserts).
category(popbar, gelato).
category(xin_xian, asianfusion).
category(xin_xian, chinese).
category(xin_xian, sushi).
category(new_china, chinese).
category(the_halal_guys, halal).
category(the_halal_guys, mideastern).
category(the_halal_guys, mediterranean).
category(wingstop, chicken_wings).
category(la_paloma, mexican).
category(sonic_drivein, hotdogs).
category(sonic_drivein, burgers).
category(sonic_drivein, icecream).
category(bleachers_sports_grill, tradamerican).
category(bleachers_sports_grill, sportsbars).
category(fish_n_tails_oyster_bar, seafood).
category(fish_n_tails_oyster_bar, bars).
category(tantuni_mediterranean_grill, mediterranean).
category(tantuni_mediterranean_grill, buffets).
category(tantuni_mediterranean_grill, turkish).
category(texaco_garland, servicestations).
category(texaco_garland, convenience).
category(taqueria_garcias, mexican).
category(davids_meat_market, meats).
category(davids_meat_market, butcher).
category(egg_roll_cafe, chinese).
category(egg_roll_cafe, hotdogs).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(judys_cafe, tradamerican).
category(judys_cafe, breakfast_brunch).
category(judys_cafe, diners).
category(chilis, tradamerican).
category(chilis, bars).
category(chilis, tex-mex).
category(desperados_mexican_restaurant_dos, mexican).
category(desperados_mexican_restaurant_dos, tex-mex).
category(picngo, convenience).
category(morning_donuts, donuts).
category(morning_donuts, bakeries).
category(morning_donuts, breakfast_brunch).
category(caprissi_pizza__pasta, pizza).
category(caprissi_pizza__pasta, pastashops).
category(jasons_deli, salad).
category(jasons_deli, delis).
category(jasons_deli, sandwiches).
category(taqueria_chimalhuacan, mexican).
category(taco_bueno, mexican).
category(taco_bueno, hotdogs).
category(taco_bueno, tex-mex).
category(sweet_shoppe_dfw, bakeries).
category(subway_restaurants, sandwiches).
category(subway_restaurants, hotdogs).
category(dominos_pizza, pizza).
category(dominos_pizza, chicken_wings).
category(dominos_pizza, sandwiches).
category(no_1_plus_chicken__richardson, chickenshop).
category(no_1_plus_chicken__richardson, korean).
category(no_1_plus_chicken__richardson, chicken_wings).
category(gonzos_cocina_mexican_grill, mexican).
category(ez_shop, grocery).
category(ez_shop, convenience).
category(lemma_coffee_roasters, coffee).
category(lemma_coffee_roasters, vegan).
category(fiesta_mart, grocery).
category(the_crab_shed, cajun).
category(the_crab_shed, seafood).
category(the_crab_shed, bars).
category(dominos_pizza, pizza).
category(dominos_pizza, chicken_wings).
category(dominos_pizza, sandwiches).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, convenience).
category(cvs_pharmacy, pharmacy).
category(indulgent_treats, desserts).
category(indulgent_treats, catering).
category(donut_depot, donuts).
category(exxon, servicestations).
category(exxon, convenience).
category(joy_kitchen, korean).
category(spring_valley_mart, restaurants).
category(subway, sandwiches).
category(lees_sandwiches, vietnamese).
category(lees_sandwiches, sandwiches).
category(lees_sandwiches, coffee).
category(mi_casita_taqueria, tacos).
category(mi_casita_taqueria, foodstands).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(jack_in_the_box, tacos).
category(student_union_dining_hall, cafeteria).
category(student_union_dining_hall, diners).
category(dashin_grocery__4, convenience).
category(frutazo_juice_bar__fruteria, juicebars).
category(frutazo_juice_bar__fruteria, vegetarian).
category(frutazo_juice_bar__fruteria, acaibowls).
category(nanas_country_citchen__catering, southern).
category(hot_crab, seafood).
category(hot_crab, cajun).
category(hot_crab, newamerican).
category(sf_supermarket, grocery).
category(m__v_quan, vietnamese).
category(cha_bong_1, restaurants).
category(banh_mi_1, vietnamese).
category(banh_mi_1, sandwiches).
category(chao_vit_thanh_da, vietnamese).
category(sieu_thi_thuan_phat, intlgrocery).
category(saigon_quan, vietnamese).
category(de_nhat_kho_bo, gourmet).
category(noodlelicious, vietnamese).
category(noodlelicious, noodles).
category(seven_eleven, servicestations).
category(seven_eleven, convenience).
category(seven_eleven, coffee).
category(hu_tieu_my_tho_restaurant, vietnamese).
category(quoc_huong_restaurant, chinese).
category(quoc_huong_restaurant, vietnamese).
category(panda_express, chinese).
category(panda_express, hotdogs).
category(moes_southwest_grill, mexican).
category(moes_southwest_grill, tex-mex).
category(ihop, breakfast_brunch).
category(ihop, tradamerican).
category(ihop, burgers).
category(bone_daddys, bbq).
category(art_bakery, bakeries).
category(art_bakery, cupcakes).
category(art_bakery, customcakes).
category(saigon_cha_lua, vietnamese).
category(saigon_cha_lua, bubbletea).
category(saigon_cha_lua, juicebars).
category(asian_buffet, buffets).
category(asian_buffet, chinese).
category(nam_hua_vietnamese_cusine, vietnamese).
category(bbq_king_restaurant, pakistani).
category(bbq_king_restaurant, bbq).
category(bbq_king_restaurant, burgers).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(subway, sandwiches).
category(starbucks, coffee).
category(tasty_egg_roll, chinese).
category(taqueria_garcias, mexican).
category(taqueria_garcias, breakfast_brunch).
category(taqueria_garcias, burgers).
category(boba_heaven, bubbletea).
category(boba_heaven, coffee).
category(boba_heaven, juicebars).
category(subway, sandwiches).
category(razzoos_cajun_cafe, cajun).
category(razzoos_cajun_cafe, seafood).
category(razzoos_cajun_cafe, burgers).
category(new_texas_king_zabiha_halal_meat_market, meats).
category(roma_palace, indpak).
category(roma_palace, venues).
category(subzi_mandi, grocery).
category(darrens_american_grill, tradamerican).
category(darrens_american_grill, burgers).
category(marcos_pizza, pizza).
category(marcos_pizza, salad).
category(marcos_pizza, chicken_wings).
category(chickfila, hotdogs).
category(banh_cuon_thang_long, vietnamese).
category(banh_cuon_thang_long, cajun).
category(seor_chachote_cantina__grill, mexican).
category(besas_italian_restaurant, pizza).
category(besas_italian_restaurant, italian).
category(frankies_mexican_cuisine, tex-mex).
category(frankies_mexican_cuisine, mexican).
category(frankies_mexican_cuisine, breakfast_brunch).
category(frankies_place, tex-mex).
category(frankies_place, mexican).
category(einstein_bros_bagels, bagels).
category(las_flamas_mexican_kitchen, mexican).
category(las_flamas_mexican_kitchen, sportsbars).
category(tom_thumb_food__pharmacy, bakeries).
category(tom_thumb_food__pharmacy, grocery).
category(tom_thumb_food__pharmacy, florists).
category(new_orleans, restaurants).
category(habesha_ethiopian_coffee, coffee).
category(ding_tea_garland, coffee).
category(ding_tea_garland, bubbletea).
category(papa_murphys, pizza).
category(starbucks, coffee).
category(tom_yum_thai, thai).
category(studio_movie_grill, movietheaters).
category(studio_movie_grill, tradamerican).
category(modern_market_eatery, breakfast_brunch).
category(modern_market_eatery, sandwiches).
category(modern_market_eatery, salad).
category(luna_grill, mediterranean).
category(luna_grill, greek).
category(luna_grill, salad).
category(pei_wei, chinese).
category(pei_wei, gluten_free).
category(pei_wei, asianfusion).
category(smashburger, burgers).
category(wendys, burgers).
category(wendys, hotdogs).
category(la_michoacana_meat_market, grocery).
category(tonys_mexican_cocina, mexican).
category(smashburger, tradamerican).
category(smashburger, burgers).
category(ihop, breakfast_brunch).
category(ihop, tradamerican).
category(ihop, burgers).
category(whole_foods_market_city_line, grocery).
category(whole_foods_market_city_line, healthmarkets).
category(whole_foods_market_city_line, coffee).
category(sonic_drivein, hotdogs).
category(sonic_drivein, burgers).
category(sonic_drivein, icecream).
category(piada_italian_street_food, italian).
category(piada_italian_street_food, salad).
category(piada_italian_street_food, wraps).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(fish_city_grill, seafood).
category(pho_is_for_lovers, vietnamese).
category(pho_is_for_lovers, asianfusion).
category(super_chix, hotdogs).
category(super_chix, chickenshop).
category(tri_tip_grill, salad).
category(tri_tip_grill, burgers).
category(tri_tip_grill, sandwiches).
category(grizzly_burger_house, burgers).
category(burgerim, burgers).
category(burgerim, chicken_wings).
category(burgerim, juicebars).
category(good_union_urban_bbq, bbq).
category(good_union_urban_bbq, beerbar).
category(good_union_urban_bbq, sandwiches).
category(shuck_n_jive, cajun).
category(shuck_n_jive, seafood).
category(jcs_burger_house, burgers).
category(donut_palace, donuts).
category(american_tap_room, beerbar).
category(american_tap_room, tapas).
category(american_tap_room, tradamerican).
category(dangki_fusion, asianfusion).
category(dangki_fusion, chicken_wings).
category(fat_straws, bubbletea).
category(fat_straws, donuts).
category(fat_straws, coffee).
category(fernandos_mexican_cuisine, tex-mex).
category(fernandos_mexican_cuisine, mexican).
category(fernandos_mexican_cuisine, breakfast_brunch).
category(walmart_supercenter, grocery).
category(walmart_supercenter, deptstores).
category(edoko_sushi__robata, sushi).
category(edoko_sushi__robata, japanese).
category(sonny_bryans_smokehouse__richardson, smokehouse).
category(jaspers_richardson, newamerican).
category(jaspers_richardson, wine_bars).
category(northside_drafthouse__eatery, pizza).
category(northside_drafthouse__eatery, beerbar).
category(northside_drafthouse__eatery, cocktailbars).
category(chard_southeast_asian_kitchen, asianfusion).
category(chard_southeast_asian_kitchen, panasian).
category(panda_express, chinese).
category(panda_express, hotdogs).
category(red_mango, juicebars).
category(red_mango, icecream).
category(nestle_toll_house_cafe_by_chip, coffee).
category(nestle_toll_house_cafe_by_chip, breakfast_brunch).
category(nestle_toll_house_cafe_by_chip, juicebars).
category(mooyah_burgers_fries__shakes, burgers).
category(tricky_fish, seafood).
category(tricky_fish, cocktailbars).
category(tricky_fish, sandwiches).
category(coolgreens, salad).
category(coolgreens, wraps).
category(coolgreens, sandwiches).
category(ediths_neighborhood_bistro, french).
category(ediths_neighborhood_bistro, cocktailbars).
category(jimmy_johns, hotdogs).
category(jimmy_johns, delis).
category(jimmy_johns, sandwiches).
category(panda_express, chinese).
category(panda_express, hotdogs).
category(delish_bubble_tea, bubbletea).
category(delish_bubble_tea, juicebars).
category(delish_bubble_tea, icecream).
category(pinto_urban_thai_diner, thai).
category(pinto_urban_thai_diner, asianfusion).
category(chopped_halal_grill, halal).
category(chopped_halal_grill, mediterranean).
category(chopped_halal_grill, mideastern).
category(dipped, desserts).
category(dipped, fooddeliveryservices).
category(dipped, catering).
category(starbucks, coffee).
category(seven_eleven, convenience).
category(seven_eleven, coffee).
category(braums_ice_cream_and_dairy_store, icecream).
category(braums_ice_cream_and_dairy_store, grocery).
category(braums_ice_cream_and_dairy_store, hotdogs).
category(el_charritos_taqueria, mexican).
category(world_food_warehouse, grocery).
category(world_food_warehouse, meats).
category(world_food_warehouse, bakeries).
category(hong_kong_bakery, bakeries).
category(walnut_food_mart, convenience).
category(tamalera_nuevo_len, mexican).
category(korys_deli, delis).
category(korys_deli, pizza).
category(dennys, breakfast_brunch).
category(dennys, tradamerican).
category(dennys, diners).
category(hong_kong_che, chinese).
category(hong_kong_che, vietnamese).
category(la_me, vietnamese).
category(doa_maria, mexican).
category(dire_dawa_cafe__restaurant, ethiopian).
category(dire_dawa_cafe__restaurant, cafes).
category(dire_dawa_cafe__restaurant, african).
category(hong_kong_market, intlgrocery).
category(mustang_softball_concessions, desserts).
category(mustang_softball_concessions, burgers).
category(golden_chick, hotdogs).
category(sprouts_farmers_market, grocery).
category(sprouts_farmers_market, healthmarkets).
category(sprouts_farmers_market, organic_stores).
category(bistro_b, vietnamese).
category(bistro_b, asianfusion).
category(bistro_b, chinese).
category(dvegan, vietnamese).
category(dvegan, vegan).
category(dvegan, vegetarian).
category(papa_johns_pizza, pizza).
category(b__p_snacks, grocery).
category(b__p_snacks, indpak).
category(tx_nutrition, coffee).
category(tx_nutrition, juicebars).
category(golden_crown, bbq).
category(olive_tree_specialty_foods, newamerican).
category(shahrzad_mediterranean_market__grill, mediterranean).
category(shahrzad_mediterranean_market__grill, persian).
category(shahrzad_mediterranean_market__grill, intlgrocery).
category(pho_95, vietnamese).
category(ice_house_beverages, beer_and_wine).
category(louis_pizza, pizza).
category(louis_pizza, tacos).
category(twenty_fourhour_pizza, pizza).
category(twenty_fourhour_pizza, chicken_wings).
category(twenty_fourhour_pizza, sandwiches).
category(tuyet_tofu, noodles).
category(tuyet_tofu, vietnamese).
category(tuyet_tofu, delis).
category(i_love_donuts, donuts).
category(albertsons, grocery).
category(the_string_bean, tradamerican).
category(the_string_bean, southern).
category(the_string_bean, comfortfood).
category(subway, sandwiches).
category(the_crab_station__dallas, seafood).
category(the_crab_station__dallas, cajun).
category(the_crab_station__dallas, bars).
category(natural_health_shop, healthmarkets).
category(natural_health_shop, grocery).
category(natural_health_shop, nutritionists).
category(lucky_bamboo_kitchen, chinese).
category(gojo_ethiopian_restaurant, ethiopian).
category(euro_delicatessen, delis).
category(euro_delicatessen, russian).
category(the_brasa_bar__grill, peruvian).
category(the_brasa_bar__grill, bars).
category(the_brasa_bar__grill, tradamerican).
category(tom_thumb, grocery).
category(tom_thumb, bakeries).
category(tom_thumb, pharmacy).
category(griffs_hamburgers, burgers).
category(masala_wok, indpak).
category(masala_wok, asianfusion).
category(masala_wok, chinese).
category(akaya_sushi_izakaya__ramen, japanese).
category(papa_murphys, pizza).
category(wingstop, chicken_wings).
category(lola_tamales__bakery, foodtrucks).
category(lola_tamales__bakery, breakfast_brunch).
category(lola_tamales__bakery, tacos).
category(monta_ramen, ramen).
category(cafe_gecko, sportsbars).
category(cafe_gecko, breakfast_brunch).
category(cafe_gecko, pizza).
category(sugarless_delite, bakeries).
category(sugarless_delite, gourmet).
category(la_madeleine_french_bakery__cafe, bakeries).
category(la_madeleine_french_bakery__cafe, breakfast_brunch).
category(la_madeleine_french_bakery__cafe, cafes).
category(kroger, drugstores).
category(kroger, grocery).
category(kroger, delis).
category(milk_and_honey, kosher).
category(milk_and_honey, grocery).
category(starbucks, coffee).
category(feng_cha__garland, bubbletea).
category(feng_cha__garland, desserts).
category(feng_cha__garland, juicebars).
category(starbucks, coffee).
category(mama_delucas, chicken_wings).
category(mama_delucas, pizza).
category(mama_delucas, pastashops).
category(fish__fizz, fishnchips).
category(fish__fizz, british).
category(cafe_amore, cafes).
category(collin_ridge_deli_shop, delis).
category(cappuccino_italian_bistro, italian).
category(cappuccino_italian_bistro, wine_bars).
category(cappuccino_italian_bistro, sandwiches).
category(long_time_ago, chinese).
category(subway, sandwiches).
category(star_food_mart, convenience).
category(donut, donuts).
category(burger_island, burgers).
category(subway, sandwiches).
category(shuri, african).
category(starbucks, coffee).
category(pei_wei, chinese).
category(pei_wei, hotdogs).
category(palios_pizza_cafe__richardson, pizza).
category(palios_pizza_cafe__richardson, italian).
category(palios_pizza_cafe__richardson, sandwiches).
category(einstein_bros_bagels, bagels).
category(taqueria_candelaria, mexican).
category(brizo, cocktailbars).
category(brizo, venues).
category(brizo, pizza).
category(homebrew_headquarters_inc, beer_and_wine).
category(homebrew_headquarters_inc, diyfood).
category(homebrew_headquarters_inc, hobbyshops).
category(taqueria_la_candelaria, mexican).
category(pollo_campero, latin).
category(pollo_campero, chickenshop).
category(pollo_campero, hotdogs).
category(sweet_frog_premium_frozen_yogurt, icecream).
category(rodeo_goat, burgers).
category(rodeo_goat, beerbar).
category(rodeo_goat, cocktailbars).
category(mi_cocina, mexican).
category(mi_cocina, tex-mex).
category(mi_cocina, breakfast_brunch).
category(wingbucket, chicken_wings).
category(ino_japanese_restaurant, japanese).
category(bambu_asian_cuisine, thai).
category(bambu_asian_cuisine, wine_bars).
category(bambu_asian_cuisine, seafood).
category(whataburger, burgers).
category(whataburger, hotdogs).
category(monster_yogurt, icecream).
category(reverie_bakeshop, desserts).
category(reverie_bakeshop, vegan).
category(reverie_bakeshop, bakeries).
category(qdoba_mexican_eats, mexican).
category(qdoba_mexican_eats, hotdogs).
category(little_greek__richardson, greek).
category(little_greek__richardson, mediterranean).
category(jersey_mikes_subs, sandwiches).
category(jersey_mikes_subs, hotdogs).
category(jersey_mikes_subs, delis).
category(jalapeno_mexican_grill, mexican).
category(tom_thumb, drugstores).
category(tom_thumb, grocery).
category(walmart_supercenter, discountstore).
category(walmart_supercenter, grocery).
category(flying_fish, seafood).
category(flying_fish, cajun).
category(saltgrass_steak_house, steak).
category(saltgrass_steak_house, seafood).
category(saltgrass_steak_house, tradamerican).
category(starbucks, coffee).
category(masons_cafe, cafes).
category(walgreens, drugstores).
category(walgreens, cosmetics).
category(walgreens, convenience).
category(mcdonalds, burgers).
category(mcdonalds, hotdogs).
category(mcdonalds, coffee).
category(imperial_cuisine, chinese).
category(pizza_hut, italian).
category(pizza_hut, pizza).
category(pizza_hut, chicken_wings).
category(tacos_el_vale, mexican).
category(jcs_burger_bar, burgers).
category(jcs_burger_bar, tacos).
category(jcs_burger_bar, bars).
category(jasons_deli, delis).
category(jasons_deli, salad).
category(jasons_deli, sandwiches).
category(richardson_farmers_market, farmersmarket).
category(high_priestess_tea_company, tea).
category(bund_wok_plano, chinese).
category(bund_wok_plano, asianfusion).
category(thai_soon_restaurant, thai).
category(tacos_y_mas, mexican).
category(tacos_y_mas, breakfast_brunch).
category(golden_star_donuts, donuts).
category(mooyah_burgers_fries__shakes, burgers).
category(mooyah_burgers_fries__shakes, icecream).
category(mooyah_burgers_fries__shakes, hotdog).
category(la_michoacana_meat_market, meats).
category(the_popcorn_shack, popcorn).
category(campisis_restaurant__coit__campbell, pizza).
category(campisis_restaurant__coit__campbell, italian).
category(curry_bliss, indpak).
category(curry_bliss, vegetarian).
category(curry_bliss, buffets).
category(dunkin, coffee).
category(dunkin, donuts).
category(baskinrobbins, icecream).
category(subway, sandwiches).
category(mooya_burger, burgers).
category(salata, salad).
category(salata, cheese).
category(salata, soup).
category(gnc, healthmarkets).
category(gnc, vitaminssupplements).
category(dickeys_barbecue_pit, tradamerican).
category(dickeys_barbecue_pit, bbq).
category(dickeys_barbecue_pit, chicken_wings).
category(angel_chicken_kitchen, chickenshop).
category(big_shucks_oyster_bar, cajun).
category(big_shucks_oyster_bar, seafood).
category(cerveceria_el_rancho, convenience).
category(dairy_queen, burgers).
category(dairy_queen, hotdogs).
category(dairy_queen, icecream).
category(chickfila, hotdogs).
category(raising_canes_chicken_fingers, hotdogs).
category(raising_canes_chicken_fingers, chicken_wings).
category(raising_canes_chicken_fingers, sandwiches).
category(little_caesars_pizza, pizza).
category(texas, steak).
category(texas, newamerican).
category(marrosso_cafe, african).
category(captain_daves_seafood_market, seafoodmarkets).
category(captain_daves_seafood_market, csa).
category(quiktrip, servicestations).
category(quiktrip, convenience).
category(quiktrip, hotdogs).
category(sweetwaters_coffee__tea_shire_blvd, coffee).
category(sweetwaters_coffee__tea_shire_blvd, desserts).
category(sweetwaters_coffee__tea_shire_blvd, cafes).
category(rockfish_seafood_grill, seafood).
category(rockfish_seafood_grill, bars).
category(rockfish_seafood_grill, cajun).
category(shared_table_coffee, coffee).
category(starbucks, coffee).
category(shopngo, convenience).
category(la_picosa, tex-mex).
category(la_picosa, mexican).
category(la_picosa, bbq).
category(elotes_fanny, mexican).
category(elotes_fanny, foodstands).
category(great_wall, chinese).
category(great_wall_super_buffet, chinese).
category(great_wall_super_buffet, buffets).
category(chipotle_mexican_grill, mexican).
category(chipotle_mexican_grill, hotdogs).
category(grocery_services_north, grocery).
category(grocery_services_north, healthmarkets).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, convenience).
category(cvs_pharmacy, pharmacy).
category(hippo, convenience).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(jack_in_the_box, tacos).
category(liberty_burger__richardson, burgers).
category(walgreens, drugstores).
category(walgreens, cosmetics).
category(walgreens, convenience).
category(corner_bakery_cafe, bakeries).
category(corner_bakery_cafe, sandwiches).
category(plano_beverage, beer_and_wine).
category(alma_liquor__market, beer_and_wine).
category(cafe_619, cafes).
category(deep_cuts, butcher).
category(anayas_seafood_scratch_kitchen, seafood).
category(ye_shire_tavern, bars).
category(ye_shire_tavern, tradamerican).
category(chilis, bars).
category(chilis, tradamerican).
category(chilis, tex-mex).
category(kosher_palate, grocery).
category(kosher_palate, delis).
category(popeyes_louisiana_kitchen, hotdogs).
category(popeyes_louisiana_kitchen, chicken_wings).
category(cindis_ny_deli__restaurant, delis).
category(cindis_ny_deli__restaurant, breakfast_brunch).
category(cindis_ny_deli__restaurant, tradamerican).
category(johns_cafe, breakfast_brunch).
category(johns_cafe, burgers).
category(johns_cafe, coffee).
category(mannys_uptown_texmex, tex-mex).
category(racetrac, servicestations).
category(racetrac, convenience).
category(sushi_rock, japanese).
category(sushi_rock, sushi).
category(m_t_a_shaved_ice, shavedice).
category(m_t_a_shaved_ice, desserts).
category(m_t_a_shaved_ice, hotdog).
category(lovers_egg_roll, asianfusion).
category(lovers_egg_roll, chinese).
category(mcalisters_deli, sandwiches).
category(mcalisters_deli, salad).
category(mcalisters_deli, delis).
category(thais_thumbz, thai).
category(donut_palace, donuts).
category(lima_taverna, peruvian).
category(lima_taverna, seafood).
category(lima_taverna, breakfast_brunch).
category(southern_recipes_grill, tradamerican).
category(southern_recipes_grill, bars).
category(southern_recipes_grill, southern).
category(sushi_go, sushi).
category(roman_cucina, italian).
category(roman_cucina, cocktailbars).
category(pizza_hut, pizza).
category(pizza_hut, italian).
category(pizza_hut, chicken_wings).
category(love_and_war_in_texas, musicvenues).
category(love_and_war_in_texas, steak).
category(love_and_war_in_texas, seafood).
category(apollonias, italian).
category(apollonias, beerbar).
category(silver_fox_steakhouse, steak).
category(silver_fox_steakhouse, seafood).
category(silver_fox_steakhouse, bars).
category(jaimes_donuts, donuts).
category(gnc, healthmarkets).
category(gnc, vitaminssupplements).
category(fino_restaurant__catering, vegetarian).
category(fino_restaurant__catering, kosher).
category(fino_restaurant__catering, italian).
category(smoothie_factory, juicebars).
category(kroger, grocery).
category(quiktrip, servicestations).
category(quiktrip, convenience).
category(quiktrip, hotdogs).
category(olive_garden_italian_restaurant, italian).
category(olive_garden_italian_restaurant, salad).
category(olive_garden_italian_restaurant, soup).
category(the_urban_grill, tradamerican).
category(jersey_mikes_subs, sandwiches).
category(jersey_mikes_subs, sandwiches).
category(jersey_mikes_subs, hotdogs).
category(jersey_mikes_subs, delis).
category(total_wine__more, beer_and_wine).
category(total_wine__more, tobaccoshops).
category(carmines_pizzeria, pizza).
category(carmines_pizzeria, salad).
category(carmines_pizzeria, sandwiches).
category(jupiter_china, chinese).
category(jupiter_china, noodles).
category(jupiter_china, sushi).
category(seven_eleven, servicestations).
category(seven_eleven, convenience).
category(seven_eleven, coffee).
category(tetco, convenience).
category(mcdonalds, coffee).
category(mcdonalds, burgers).
category(mcdonalds, hotdogs).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, convenience).
category(seven_eleven, coffee).
category(chinos_tacos, tacos).
category(pizza_patrn, pizza).
category(pizza_patrn, chicken_wings).
category(pizza_patrn, desserts).
category(tandoori_pizza, indpak).
category(tandoori_pizza, pizza).
category(tandoori_pizza, burgers).
category(hot_pancakes, breakfast_brunch).
category(hot_pancakes, burgers).
category(hot_pancakes, hotdogs).
category(hooters, tradamerican).
category(hooters, sportsbars).
category(hooters, chicken_wings).
category(starbucks, coffee).
category(hooties_burger_bar, fooddeliveryservices).
category(hooties_burger_bar, burgers).
category(mr_wongs_chicken__rice, chinese).
category(mr_wongs_chicken__rice, chicken_wings).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(taqueria_y_restaurante_el_paisano, mexican).
category(cuquitas_restaurant, mexican).
category(chevron_mart, convenience).
category(la_salsa_verde_taqueria, mexican).
category(donuts, donuts).
category(simons_sushi, japanese).
category(simons_sushi, sushi).
category(el_fenix, mexican).
category(el_fenix, tex-mex).
category(pho_s_cowboys, vietnamese).
category(pho_s_cowboys, seafood).
category(chocolate_angel_cafe__tea_room__high_street, bakeries).
category(chocolate_angel_cafe__tea_room__high_street, tea).
category(phuong_nam_restaurant, vietnamese).
category(phuong_nam_restaurant, noodles).
category(phuong_nam_restaurant, karaoke).
category(kezira_cafe, ethiopian).
category(kezira_cafe, african).
category(noodle_wave, thai).
category(noodle_wave, seafood).
category(noodle_wave, soup).
category(burger_king, hotdogs).
category(burger_king, burgers).
category(fiesta_mart, grocery).
category(taco_bueno, mexican).
category(taco_bueno, hotdogs).
category(taco_bueno, tex-mex).
category(shishkabobs_cafe, persian).
category(shishkabobs_cafe, mediterranean).
category(shishkabobs_cafe, buffets).
category(pho_ca_dao, vietnamese).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(jack_in_the_box, tacos).
category(my_canh_chinese_restaurant, chinese).
category(my_canh_chinese_restaurant, vietnamese).
category(parripollo_country, newamerican).
category(pollo_regio, mexican).
category(pollo_regio, chickenshop).
category(hiep_phong_bbq, vietnamese).
category(hiep_phong_bbq, chinese).
category(hiep_phong_bbq, bbq).
category(baleadas_by_lilis, latin).
category(nunos_tacos__vegmex_grill, vegan).
category(nunos_tacos__vegmex_grill, tacos).
category(nunos_tacos__vegmex_grill, tex-mex).
category(paleteria_san_marcos, desserts).
category(paleteria_san_marcos, icecream).
category(paleteria_san_marcos, importedfood).
category(q_w_b, servicestations).
category(q_w_b, convenience).
category(cicis, pizza).
category(circle_k, convenience).
category(circle_k, servicestations).
category(highland_springs, restaurants).
category(churchs_chicken, hotdogs).
category(churchs_chicken, chicken_wings).
category(chu_chu_grocery_spices__catering, grocery).
category(chu_chu_grocery_spices__catering, catering).
category(burger_king, burgers).
category(burger_king, hotdogs).
category(jupiter_liquor, beer_and_wine).
category(kim_ninh_bakery, bakeries).
category(chu_chu_grocery, grocery).
category(woo_mee_ok_korean_bbq, korean).
category(woo_mee_ok_korean_bbq, bbq).
category(popeyes_louisiana_kitchen, hotdogs).
category(popeyes_louisiana_kitchen, chicken_wings).
category(the_boiling_crab, cajun).
category(the_boiling_crab, seafood).
category(bida_rang_dong, poolhalls).
category(bida_rang_dong, vietnamese).
category(ice_vendors, icecream).
category(el_rancho, grocery).
category(e__s_grocery, grocery).
category(charcoal_avenue, newamerican).
category(charcoal_avenue, mediterranean).
category(charcoal_avenue, indpak).
category(quick_shop, intlgrocery).
category(tejano_bbq__more, bbq).
category(tejano_bbq__more, mexican).
category(mcdonalds, burgers).
category(mcdonalds, hotdogs).
category(mcdonalds, coffee).
category(tikka_n_kabab, pakistani).
category(tikka_n_kabab, burgers).
category(tikka_n_kabab, indpak).
category(genghis_grill, mongolian).
category(genghis_grill, chinese).
category(genghis_grill, asianfusion).
category(la_paloma_taqueria, mexican).
category(in_the_mix_bakery, bakeries).
category(burger_king, burgers).
category(burger_king, hotdogs).
category(gnc, healthmarkets).
category(gnc, vitaminssupplements).
category(eggroll_express, chinese).
category(eggroll_express, hotdogs).
category(jasons_deli, delis).
category(jasons_deli, salad).
category(jasons_deli, sandwiches).
category(candy_land, candy).
category(aldeez_caribbean_restaurant__event_center, caribbean).
category(aldeez_caribbean_restaurant__event_center, african).
category(aldeez_caribbean_restaurant__event_center, musicvenues).
category(northpoint_fresh_market_deli, delis).
category(ihop, tradamerican).
category(ihop, breakfast_brunch).
category(ihop, burgers).
category(southwest_farmers_market, farmersmarket).
category(corner_food_mart, grocery).
category(cafe_mouyyad, coffee).
category(taco_bueno, mexican).
category(taco_bueno, hotdogs).
category(taco_bueno, tex-mex).
category(panera_bread, sandwiches).
category(panera_bread, salad).
category(panera_bread, soup).
category(c_store_no_11, convenience).
category(philly_connection, cheesesteaks).
category(taqueria_la_casita, mexican).
category(waffle_house, breakfast_brunch).
category(waffle_house, waffles).
category(waffle_house, tradamerican).
category(angels_beverage_center, beer_and_wine).
category(la_poblanita_mexican_bakery, bakeries).
category(master_wok, chinese).
category(tortilleria_la_nueva_puntada, mexican).
category(nest_burger, burgers).
category(schlotzskys, delis).
category(schlotzskys, sandwiches).
category(schlotzskys, catering).
category(kayio, asianfusion).
category(outback_steakhouse, steak).
category(red_lobster, seafood).
category(red_lobster, tradamerican).
category(enchiladas_restaurant__catering, mexican).
category(chipotle_mexican_grill, mexican).
category(chipotle_mexican_grill, hotdogs).
category(souper_salad, salad).
category(souper_salad, soup).
category(souper_salad, buffets).
category(guanaquitas, tacos).
category(guanaquitas, salvadoran).
category(wok_express, restaurants).
category(one_stop_food_store, convenience).
category(olive_garden_italian_restaurant, italian).
category(olive_garden_italian_restaurant, salad).
category(olive_garden_italian_restaurant, soup).
category(pangea_restaurant__bar, bars).
category(pangea_restaurant__bar, newamerican).
category(saigon_world_bakery, bakeries).
category(garden_restaurant, dimsum).
category(dong_hai_chinese_restaurant, chinese).
category(pizza_hut, pizza).
category(pizza_hut, italian).
category(pizza_hut, chicken_wings).
category(sonic_drivein, hotdogs).
category(sonic_drivein, burgers).
category(sonic_drivein, icecream).
category(pho_bang_restaurant, vietnamese).
category(aqua_fresh_water_store, waterstores).
category(pollo_regio, mexican).
category(pollo_regio, chickenshop).
category(aldi, grocery).
category(aldi, markets).
category(aldi, organic_stores).
category(dong_que, vietnamese).
category(truong_nguyen_market, grocery).
category(viet_tofu, vietnamese).
category(northcreek_sandwich_shop, delis).
category(northcreek_sandwich_shop, sandwiches).
category(qq_cafe, coffee).
category(la_xanh_restaurant, soup).
category(la_xanh_restaurant, chinese).
category(la_xanh_restaurant, vietnamese).
category(daylight_donuts, donuts).
category(truong_nguyen, grocery).
category(sharks_fish__chicken, chicken_wings).
category(sharks_fish__chicken, fishnchips).
category(taqueria_el_sabroso, tex-mex).
category(taqueria_el_sabroso, mediterranean).
category(tokyo_harbor, sushi).
category(tokyo_harbor, bars).
category(tokyo_harbor, japanese).
category(first_chinese_bbq, chinese).
category(paesanos_cafe, restaurants).
category(i_love_egg_rolls, newamerican).
category(i_love_egg_rolls, chinese).
category(taco_casa, mexican).
category(circle_k, convenience).
category(scooters_coffee, coffee).
category(kazys_gourmet_shop, intlgrocery).
category(the_sushi_bar, sushi).
category(banh_trang_tron_dallas, foodtrucks).
category(kickin_crab, seafood).
category(kickin_crab, cajun).
category(villa_monterrey_restaurant, mexican).
category(villa_monterrey_restaurant, breakfast_brunch).
category(villa_monterrey_restaurant, burgers).
category(golden_chick, hotdogs).
category(golden_chick, southern).
category(golden_chick, tradamerican).
category(sayaka_steak__sushi, japanese).
category(sayaka_steak__sushi, sushi).
category(paleteria_super_smash_ice_cream_and_shaved_ice, shavedice).
category(paleteria_super_smash_ice_cream_and_shaved_ice, icecream).
category(tocotoco_boba_tea, desserts).
category(tocotoco_boba_tea, bubbletea).
category(bien_xanh, vietnamese).
category(bien_xanh, karaoke).
category(bjs_restaurant__brewhouse, newamerican).
category(bjs_restaurant__brewhouse, breweries).
category(racetrac, convenience).
category(pho_21_noodles__grills, vietnamese).
category(la_paloma_taqueria, mexican).
category(cookies_by_design, desserts).
category(cookies_by_design, flowers).
category(lus_kitchen, asianfusion).
category(hu_tieu_nam_vang, vietnamese).
category(hu_tieu_nam_vang, noodles).
category(hu_tieu_nam_vang, soup).
category(a_n_s_fina, convenience).
category(taco_cabana, mexican).
category(duc_huong_gio_cha, vietnamese).
category(ngon_bistro, vietnamese).
category(hiep_thai_food_store, seafoodmarkets).
category(hiep_thai_food_store, markets).
category(hiep_thai_food_store, intlgrocery).
category(acn_herbs__eastern_tradition_chinese_herbs, healthmarkets).
category(big_mamas_chicken__waffles, soulfood).
category(doan_restaurant, vietnamese).
category(swadeshi_indian_cuisine, indpak).
category(sarahs_caf__panini, juicebars).
category(sarahs_caf__panini, breakfast_brunch).
category(sarahs_caf__panini, tradamerican).
category(ibex_ethiopian_cuisine_and_bar, ethiopian).
category(delicious_deli, delis).
category(delicious_deli, sandwiches).
category(bos_chicken__seafood, hotdogs).
category(bos_chicken__seafood, seafood).
category(ba_le_restaurant__bakery, vietnamese).
category(ba_le_restaurant__bakery, bakeries).
category(ba_le_restaurant__bakery, sandwiches).
category(the_dark_chocolate_bakery, bakeries).
category(the_dark_chocolate_bakery, desserts).
category(egg_stand, foodtrucks).
category(egg_stand, burgers).
category(egg_stand, catering).
category(pie_flutin_pastries, bakeries).
category(quoc_bao_bakery, bakeries).
category(quoc_bao_bakery, vietnamese).
category(quoc_bao_bakery, sandwiches).
category(pizza_patrn, pizza).
category(pizza_patrn, chicken_wings).
category(pizza_patrn, desserts).
category(e_z_shop, convenience).
category(einstein_bros_bagels, bagels).
category(einstein_bros_bagels, coffee).
category(seven_eleven, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, coffee).
category(pizza_patrn, pizza).
category(pizza_patrn, chicken_wings).
category(pizza_patrn, desserts).
category(fish_n_tails_oyster_bar, seafood).
category(tasty_asia_restaurant, asianfusion).
category(tasty_asia_restaurant, chinese).
category(tasty_asia_restaurant, vietnamese).
category(tasty_china, chinese).
category(grillmasters_meat, meats).
category(golden_chick, hotdogs).
category(chickfila, hotdogs).
category(com_tam_thuan_kieu, vietnamese).
category(la_madeleine_french_bakery__cafe, cafes).
category(la_madeleine_french_bakery__cafe, bakeries).
category(la_madeleine_french_bakery__cafe, breakfast_brunch).
category(sky_rocket_burger, burgers).
category(hot_and_creamy_donuts, bakeries).
category(hot_and_creamy_donuts, donuts).
category(raising_canes_chicken_fingers, hotdogs).
category(raising_canes_chicken_fingers, chicken_wings).
category(central_market, grocery).
category(whataburger, burgers).
category(whataburger, hotdogs).
category(kim_lan_food_to_go, vietnamese).
category(kumars__plano, indpak).
category(kumars__plano, juicebars).
category(hu_tieu_my_tho, vietnamese).
category(trak_10, convenience).
category(quiktrip, servicestations).
category(quiktrip, convenience).
category(quiktrip, hotdogs).
category(tai_zong_si_chuan, szechuan).
category(taco_express, mexican).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(jack_in_the_box, tacos).
category(los_compadres_taqueria, mexican).
category(jack_in_the_box, hotdogs).
category(jack_in_the_box, burgers).
category(jack_in_the_box, tacos).
category(mcdonalds, burgers).
category(mcdonalds, hotdogs).
category(mcdonalds, coffee).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(taco_bell, mexican).
category(taco_bell, hotdogs).
category(walmart_supercenter, grocery).
category(walmart_supercenter, deptstores).
category(saigon_deli, vietnamese).
category(seven_eleven, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, coffee).
category(la_super_paleteria, icecream).
category(wuden_chopsticks, asianfusion).
category(wuden_chopsticks, foodtrucks).
category(potbelly_sandwich_shop, sandwiches).
category(potbelly_sandwich_shop, hotdogs).
category(potbelly_sandwich_shop, salad).
category(boston_market, comfortfood).
category(boston_market, tradamerican).
category(boston_market, sandwiches).
category(desta_ethiopian_restaurant, ethiopian).
category(desta_ethiopian_restaurant, bars).
category(desta_ethiopian_restaurant, breakfast_brunch).
category(kfc, hotdogs).
category(kfc, chicken_wings).
category(kfc, chickenshop).
category(stone_pit_wings, salad).
category(stone_pit_wings, tradamerican).
category(stone_pit_wings, chicken_wings).
category(quiktrip, servicestations).
category(quiktrip, convenience).
category(quiktrip, hotdogs).
category(fusion_sichuan_cuisine, asianfusion).
category(fusion_sichuan_cuisine, chinese).
category(el_pollo_loco, hotdogs).
category(el_pollo_loco, mexican).
category(daddy_bobs_catfish, seafood).
category(urban_rio_cantina__grill, tex-mex).
category(urban_rio_cantina__grill, mexican).
category(urban_rio_cantina__grill, beerbar).
category(long_john_silvers, seafood).
category(long_john_silvers, hotdogs).
category(grandys, breakfast_brunch).
category(grandys, hotdogs).
category(jgs_old_fashioned_hamburgers, burgers).
category(jgs_old_fashioned_hamburgers, tradamerican).
category(jgs_old_fashioned_hamburgers, southern).
category(fish_shack, seafood).
category(on_the_border_mexican_grill__cantina, mexican).
category(on_the_border_mexican_grill__cantina, tex-mex).
category(el_rancho_supermercado, grocery).
category(abugeda_grocery, grocery).
category(tacqueria_nuevo_len, mexican).
category(ostioneria_7_mares, mexican).
category(churchs_chicken, chicken_wings).
category(churchs_chicken, hotdogs).
category(sushi_ichiban, japanese).
category(sushi_ichiban, sushi).
category(retro_taco, tex-mex).
category(retro_taco, mexican).
category(retro_taco, empanadas).
category(williams_chicken, chicken_wings).
category(chipotle_mexican_grill, hotdogs).
category(chipotle_mexican_grill, mexican).
category(starbucks, coffee).
category(normas_cafe, diners).
category(normas_cafe, desserts).
category(normas_cafe, breakfast_brunch).
category(arbys, sandwiches).
category(arbys, hotdogs).
category(subway, sandwiches).
category(vivi_bubble_tea, bubbletea).
category(sakura_chinese_bbq, chinese).
category(sakura_chinese_bbq, bbq).
category(sakura_chinese_bbq, noodles).
category(taco_cabana, mexican).
category(dantes_italian_eatery, pizza).
category(dantes_italian_eatery, italian).
category(smoothie_king, juicebars).
category(smoothie_king, healthmarkets).
category(seven_eleven, servicestations).
category(seven_eleven, convenience).
category(seven_eleven, coffee).
category(wus_super_bowl, chinese).
category(wus_super_bowl, seafood).
category(starbucks, coffee).
category(city_cafe__bakery, ethiopian).
category(city_cafe__bakery, breakfast_brunch).
category(city_cafe__bakery, cakeshop).
category(captain_ds, seafood).
category(starbucks, coffee).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(whataburger, hotdogs).
category(whataburger, burgers).
category(subway, sandwiches).
category(dominos_pizza, pizza).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(outback_steakhouse, steak).
category(mcdonalds, hotdogs).
category(mcdonalds, burgers).
category(mcdonalds, coffee).
category(eddys_pizza_restaurant, pizza).
category(eddys_pizza_restaurant, italian).
category(uni_sushi, sushi).
category(pink_coffee, desserts).
category(pink_coffee, bakeries).
category(pink_coffee, coffee).
category(kegs__barrels, beer_and_wine).
category(hub_streat, breakfast_brunch).
category(hub_streat, tradamerican).
category(hub_streat, newamerican).
category(georgias_farmers_market, farmersmarket).
category(garland_cafe, tradamerican).
category(garland_cafe, breakfast_brunch).
category(garland_cafe, cafes).
category(red_seven_convenience_store, convenience).
category(morning_donuts, donuts).
category(ruang_thai, thai).
category(ruang_thai, salad).
category(ruang_thai, seafood).
category(urban_nutrition_lounge, juicebars).
category(gogiya, korean).
category(gogiya, bbq).
category(gogiya, hotpot).
category(mcdonalds, burgers).
category(mcdonalds, hotdogs).
category(mcdonalds, coffee).
category(maries_kitchen, filipino).
category(maries_kitchen, salad).
category(maries_kitchen, sandwiches).
category(popeyes_louisiana_kitchen, hotdogs).
category(popeyes_louisiana_kitchen, chicken_wings).
category(taco_bell, mexican).
category(taco_bell, hotdogs).
category(urban_crust, pizza).
category(urban_crust, lounges).
category(urban_crust, italian).
category(the_fillmore_pub, tradamerican).
category(the_fillmore_pub, salad).
category(the_fillmore_pub, irish_pubs).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(burger_bueno, burgers).
category(cvs_pharmacy, drugstores).
category(cvs_pharmacy, pharmacy).
category(cvs_pharmacy, convenience).
category(the_boiling_crab, seafood).
category(the_boiling_crab, cajun).
category(ye_ole_butcher_shop, meats).
category(ye_ole_butcher_shop, burgers).
category(cotton_candy_donuts, donuts).
category(cotton_candy_donuts, breakfast_brunch).
category(cotton_candy_donuts, bakeries).
category(better_than_sex__a_dessert_restaurant_plano, desserts).
category(dickeys_barbecue_pit, bbq).
category(dickeys_barbecue_pit, tradamerican).
category(dickeys_barbecue_pit, chicken_wings).
category(fourteeneighteencoffee_house, coffee).
category(fourteeneighteencoffee_house, sandwiches).
category(fourteeneighteencoffee_house, desserts).
category(yegna_juice_bar, juicebars).
category(gracious_baking, bakeries).
category(gracious_baking, customcakes).
category(gracious_baking, desserts).
category(sini_coffee_lounge, ethiopian).
category(sini_coffee_lounge, coffee).
category(taco_bell, hotdogs).
category(taco_bell, mexican).
category(viet_quan, vietnamese).
category(wingstop, chicken_wings).
category(lockhart_smokehouse, bbq).
category(lockhart_smokehouse, smokehouse).
category(zalat_pizza, pizza).
category(zalat_pizza, italian).
category(the_gelato_cone, icecream).
category(the_gelato_cone, juicebars).
category(taco_chaco_4, mexican).
category(rosas_caf__tortilla_factory, mexican).
category(rosas_caf__tortilla_factory, tex-mex).
category(rosas_caf__tortilla_factory, breakfast_brunch).
category(fcking_good_pizza, fooddeliveryservices).
category(fcking_good_pizza, pizza).
category(ebesu_robatasushi, sushi).
category(ebesu_robatasushi, izakaya).
category(trompo_taqueria__burgers, mexican).
category(trompo_taqueria__burgers, burgers).
category(seven_eleven, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, coffee).
category(daylight_donuts, donuts).
category(daylight_donuts, bakeries).
category(subway, sandwiches).
category(xo_coffee_company, coffee).
category(xo_coffee_company, breakfast_brunch).
category(xo_coffee_company, tradamerican).
category(pho_95_restaurant, vietnamese).
category(vickery_park_plano, bars).
category(vickery_park_plano, tradamerican).
category(sams_club, wholesale_stores).
category(sams_club, grocery).
category(sams_club, tires).
category(jorgs_cafe_vienna, german).
category(jorgs_cafe_vienna, austrian).
category(kfc, hotdogs).
category(kfc, chicken_wings).
category(kfc, chickenshop).
category(sushi_town, sushi).
category(sushi_town, japanese).
category(apple_spice, fooddeliveryservices).
category(apple_spice, catering).
category(kfc, hotdogs).
category(kfc, chicken_wings).
category(kfc, chickenshop).
category(pizza, pizza).
category(pizza, italian).
category(sarah_emilys_home_baked_cookies, bakeries).
category(freds_downtown_philly, newamerican).
category(freds_downtown_philly, cheesesteaks).
category(freds_downtown_philly, tradamerican).
category(primo_brothers_pizza, pizza).
category(primo_brothers_pizza, italian).
category(primo_brothers_pizza, pastashops).
category(sweetbasil_thai_kitchen__garland, thai).
category(sweetbasil_thai_kitchen__garland, noodles).
category(hawaiian_bros, hawaiian).
category(wannaeat_seafood, soulfood).
category(wannaeat_seafood, seafood).
category(wingstop, chicken_wings).
category(sicilianos_a_taste_of_italy, italian).
category(sicilianos_a_taste_of_italy, bars).
category(sicilianos_a_taste_of_italy, seafood).
category(seven_eleven, convenience).
category(seven_eleven, servicestations).
category(seven_eleven, coffee).
category(bernards_gourmet_foods, gourmet).
category(bernards_gourmet_foods, popupshops).
category(lalibela_ethiopian_restaurant, ethiopian).
category(asian_thai_2_go, thai).
category(abyssinia_gebya, grocery).
category(in_the_cut_cafe, soulfood).
category(in_the_cut_cafe, southern).
category(tlc_vegan_kitchen, fooddeliveryservices).
category(tlc_vegan_kitchen, catering).
category(good_wings, chicken_wings).
category(good_wings, fooddeliveryservices).
category(meat_point, kosher).
category(meat_point, steak).
category(meat_point, mediterranean).
category(starbucks, coffee).
category(ricks_old_fashioned_burgers, burgers).
category(ricks_old_fashioned_burgers, breakfast_brunch).
category(ricks_old_fashioned_burgers, sandwiches).
category(burger_king, hotdogs).
category(burger_king, burgers).
category(cafe_biarritz, coffee).
category(golden_chick, hotdogs).