rating(far_east_pizza, 3.0).
rating(la_cuisine_cafe, 2.0).
rating(cafe_max_richardson, 4.0).
rating(ten50_bbq, 3.5).
rating(abu_omar_halal, 3.5).
rating(texas_smokehouse_barbque, 3.5).
rating(sweet_donuts, 4.5).
rating(subway, 1.5).
rating(orchard_at_the_office, 5.0).
rating(andalous_mediterranean_buffet, 4.0).
rating(buffet_at_international_buddhist_progress_society, 3.0).
rating(the_house_cafe, 4.0).
rating(water_drop_teahouse, 5.0).
rating(four_bullets_brewery, 4.5).
rating(big_d_kona_ice, 5.0).
rating(arapaho_deli, 5.0).
rating(eiland_coffee_roasters, 5.0).
rating(new_york_eats, 4.0).
rating(urban_eatz, 3.5).
rating(sakhuu_thai, 4.5).
rating(yoshi_shabu_shabu, 4.5).
rating(bawarchi_biryanis, 3.5).
rating(the_wingd_nut, 4.0).
rating(tiffs_treats, 4.0).
rating(sweet_mix_desserts, 4.0).
rating(menas_texmex_grill_cantina, 4.5).
rating(yumilicious, 4.5).
rating(potbelly_sandwich_shop, 3.5).
rating(starbucks, 3.0).
rating(burger_king, 2.0).
rating(russos_coal_fired_italian_kitchen, 3.0).
rating(jersey_mikes_subs, 3.5).
rating(seven_eleven, 4.5).
rating(twisted_root_burger__richardson, 3.5).
rating(panera_bread, 3.0).
rating(chipotle_mexican_grill, 3.5).
rating(jimmy_johns, 3.5).
rating(velvet_taco_richardson, 4.0).
rating(chickfila, 3.0).
rating(mcdonalds, 2.0).
rating(seven_eleven, 2.5).
rating(dimassis_mediterranean_buffet, 3.5).
rating(zoes_kitchen, 3.5).
rating(the_great_outdoors_sub_shop, 3.5).
rating(boots_and_brix, 2.5).
rating(tapioca_house, 3.0).
rating(taco_cabana, 2.0).
rating(first_watch, 3.5).
rating(genroku_sushi__grill, 4.0).
rating(below_40_fresh_kitchen, 4.5).
rating(mumtaz_indian_restaurant, 4.0).
rating(aahar_indian_restaurant, 3.0).
rating(i_fratelli_pizza_richardson, 4.0).
rating(paris_donuts, 4.0).
rating(sichuan_king, 4.0).
rating(canton_chinese_restaurant, 3.5).
rating(which_wich_superior_sandwiches, 3.0).
rating(kolache_factory, 4.0).
rating(freshii, 4.5).
rating(freebirds_world_burrito, 3.0).
rating(spin_pizza, 4.0).
rating(smoothie_factory, 1.0).
rating(fox__hound, 3.5).
rating(the_pie_pop_company, 5.0).
rating(maru_ramen, 4.0).
rating(smoothie_king, 3.5).
rating(snuffers, 3.5).
rating(asian_mint, 4.0).
rating(torchys_tacos, 3.5).
rating(snappy_salads, 4.0).
rating(taco_ocho, 4.0).
rating(nothing_bundt_cakes, 4.5).
rating(pho_que_huong, 3.5).
rating(teriyaki_sensei, 4.0).
rating(tofu_factory_korean_cuisine, 4.5).
rating(first_watch, 4.0).
rating(tkk_fried_chicken, 3.5).
rating(kung_fu_tea, 4.0).
rating(jeng_chi_restaurant, 4.0).
rating(eightyfivec_bakery_cafe, 4.0).
rating(java_land_coffee_haus, 3.5).
rating(royal_sichuan, 3.5).
rating(international_bakery__sandwich_bar, 5.0).
rating(burning_rice, 4.5).
rating(pho_corner, 3.0).
rating(wendys, 4.0).
rating(good_fortune_supermarket, 3.0).
rating(bennys_bagels, 3.0).
rating(palapas_seafood_bar, 3.5).
rating(golden_chick, 3.5).
rating(cafe_brazil, 3.0).
rating(masala_twist, 3.5).
rating(pho_ok, 4.5).
rating(sushi_sake, 4.0).
rating(olive_burger__richardson, 4.5).
rating(spice_n_rice_indian_cuisine, 4.0).
rating(mein_cuisine, 2.5).
rating(taiwan_cafe, 3.5).
rating(vila_brazil_steak_house, 4.5).
rating(dominos_pizza, 3.5).
rating(jack_in_the_box, 1.5).
rating(pho_truong, 4.0).
rating(custer_wok, 2.5).
rating(ali_baba_mediterranean_grill, 4.5).
rating(hometown_cafe, 4.0).
rating(dickeys_barbecue_pit, 2.5).
rating(tongue_in_cheek_ice_cream, 4.5).
rating(taco_bell, 2.0).
rating(chien_garden, 4.0).
rating(albaghdady_bakery, 4.0).
rating(seven_eleven, 1.5).
rating(lohas_teriyaki, 4.5).
rating(buy_low_food_mart__beer, 4.5).
rating(tineo_peruvian_cafe, 4.0).
rating(pinedas_mexican_cuisine, 4.5).
rating(burger_island, 4.0).
rating(cajun_corner, 3.5).
rating(anatolia_mart, 4.0).
rating(lonestar_grill__sports_cafe, 3.5).
rating(tacos_y_mas, 3.0).
rating(dominos_pizza, 3.0).
rating(oriental_express, 3.5).
rating(kebabnkurry, 3.5).
rating(spring_creek_barbeque, 3.5).
rating(salvadorian_cuisine, 4.0).
rating(kasra_persian_restaurant, 3.5).
rating(dollar_general_store, 5.0).
rating(austin_avenue_grill__sports_bar, 2.5).
rating(la_casita_bakeshop, 5.0).
rating(los_merla_bakery, 5.0).
rating(zaks_donuts, 4.0).
rating(trouvi_cookie_company, 5.0).
rating(cocina_de_mi_casa, 4.5).
rating(amigos_restaurant, 4.0).
rating(alon, 4.0).
rating(holy_frijoles, 3.5).
rating(pho_long_noodle_and_grill, 4.5).
rating(hat_creek_burger_company, 3.5).
rating(the_line, 4.0).
rating(meat_maniac, 5.0).
rating(creamy_doughnuts, 4.5).
rating(grand_cafe, 4.5).
rating(ken_japanese_bistro, 4.5).
rating(afrah_restaurant, 4.0).
rating(vroom_vroom_valero, 3.5).
rating(ziggys_tavern, 1.0).
rating(arbys, 3.0).
rating(fish_shack, 4.0).
rating(tavern_on_main_street, 3.5).
rating(krab_kingz_7, 4.5).
rating(habibi_cafe, 2.0).
rating(jasmine_cafe__hookah_lounge, 3.5).
rating(dallas_king_daddy_ice, 5.0).
rating(joy_donuts, 4.5).
rating(indo_pak_super_market, 3.5).
rating(indo_pak_cafe, 3.0).
rating(medina_moroccan_and_mediterranean_fusion, 4.5).
rating(murphys_deli, 1.0).
rating(yummy_burgers__bbq, 4.0).
rating(isabellys_sweet_treats, 4.0).
rating(first_chinese_bbq, 3.5).
rating(boba_latte, 4.0).
rating(m2m_bakery, 4.5).
rating(albaghdady, 4.5).
rating(lockwood_distilling, 4.5).
rating(communion_neighborhood_cooperative, 4.0).
rating(dels_charcoal_burgers, 4.5).
rating(subway, 2.0).
rating(sultan_caf, 3.5).
rating(new_world_realty, 1.0).
rating(fratello_halal_pizza__grill, 3.5).
rating(chameli, 3.5).
rating(kings_noodle, 4.0).
rating(wound_up_cafe, 5.0).
rating(creamy_taste_of_heaven, 5.0).
rating(sweetstop, 4.5).
rating(smoothie_factory, 3.0).
rating(pho_tay_do, 4.0).
rating(monkey_king_noodle_company, 4.5).
rating(first_emperor_chinese_restaurant, 4.0).
rating(la_burger, 4.5).
rating(bulldog_katsu, 4.5).
rating(jamaica_cabana_restaurant, 4.0).
rating(marias_bakery, 4.5).
rating(gopal_vegetarian_restaurant, 4.0).
rating(burger_street, 3.5).
rating(al_basha_mediterranean_restaurant, 3.5).
rating(quiktrip, 4.0).
rating(masami, 4.0).
rating(starbucks, 2.5).
rating(mcdonalds, 1.5).
rating(fish_n_tails_oyster_bar, 4.0).
rating(kirin_court_chinese_restaurant, 3.5).
rating(mmch_richardson, 4.0).
rating(stephanies_kitchen, 5.0).
rating(krispy_kreme, 2.5).
rating(richardson_beer__wine, 4.0).
rating(pizza_hut, 1.5).
rating(onetwothree_street_food, 4.5).
rating(royal_sweets__fast_food, 3.0).
rating(subway, 2.5).
rating(subway, 3.0).
rating(addis_abeba_ethiopian_restaurant, 4.0).
rating(abocas_italian_grill, 4.0).
rating(industrial_pizza__brew, 4.5).
rating(fusion_vibes_kitchen__bar, 4.5).
rating(eileens_pralines, 4.5).
rating(the_chefs_cuisine, 5.0).
rating(jababae_food_truck, 4.0).
rating(mcdonalds, 2.5).
rating(pho_bac_restaurant, 4.0).
rating(chiloso_mexican_bistro__richardson, 3.0).
rating(cafe_cali, 1.0).
rating(bikaner_sweets, 4.5).
rating(hot_breads, 1.0).
rating(one_hummus, 4.0).
rating(victor_hugos, 5.0).
rating(vegvana, 4.0).
rating(little_caesars_pizza, 2.5).
rating(porta_di_roma, 3.5).
rating(bangkok_at_beltline, 4.0).
rating(parks_donuts, 5.0).
rating(dos_charros_restaurant, 4.0).
rating(glory_chinese_restaurant, 3.0).
rating(olive_oils_pizzeria, 3.5).
rating(gong_cha, 3.5).
rating(fuzzys_taco_shop, 3.0).
rating(i_love_u_alatte, 4.5).
rating(sweet_daze_dessert_bar, 3.5).
rating(smoothie_king, 3.0).
rating(alamo_drafthouse_cinema_richardson, 4.0).
rating(applebees_grill__bar, 3.0).
rating(jimmy_johns, 3.0).
rating(cake_carousel, 4.0).
rating(cinnaholic, 4.5).
rating(flaming_buffet, 3.5).
rating(haystack_burgers__barley, 4.0).
rating(rickys_hot_chicken, 4.5).
rating(cream_and_crepes_cafe, 4.5).
rating(guitars__growlers, 4.5).
rating(hoki_poki, 4.5).
rating(ding_tea__richardson, 4.5).
rating(wendys, 2.5).
rating(mezza_cafe, 4.0).
rating(tasty_tails, 4.0).
rating(campbell_donuts, 5.0).
rating(woody_bs_mesquite_bbq, 4.5).
rating(india_bazaar, 4.0).
rating(cafe_bleu, 3.5).
rating(docs_food_store, 5.0).
rating(chocolate_angel_cafe__tea_room, 3.5).
rating(pho_pasteur, 4.0).
rating(el_pollo_loco, 3.5).
rating(chipotle_mexican_grill, 1.5).
rating(golden_joy_bbq, 3.5).
rating(cvs_pharmacy, 2.0).
rating(thai_asian_fusion_cafe, 3.5).
rating(firehouse_subs, 4.0).
rating(sharetea, 4.0).
rating(quiznos, 4.0).
rating(waffle_olicious, 4.0).
rating(aldi, 4.0).
rating(natural_grocers, 4.0).
rating(four_season_farmers_market, 3.5).
rating(raising_canes_chicken_fingers, 3.0).
rating(bliss_street_bakery, 5.0).
rating(whataburger, 2.5).
rating(bigdash_ice_cream__pastries, 5.0).
rating(mcdonalds, 2.5).
rating(sigels, 4.0).
rating(zaxbys_chicken_fingers__buffalo_wings, 3.0).
rating(sonic_drivein, 3.0).
rating(pizza_americana, 4.0).
rating(flaming_skewer, 5.0).
rating(braums_ice_cream__dairy_stores, 3.5).
rating(panda_express, 2.5).
rating(danang_souphouse, 3.5).
rating(gnc, 3.5).
rating(papa_johns_pizza, 1.5).
rating(walgreens, 3.0).
rating(pizza_hut, 2.0).
rating(long_john_silvers, 3.0).
rating(pappas_catering, 4.5).
rating(pappasitos_cantina, 3.5).
rating(taco_bell, 2.5).
rating(wingstop, 2.0).
rating(tom_thumb_food__pharmacy, 2.5).
rating(roccos_italian_caf, 4.5).
rating(meteor_hamburgers, 4.0).
rating(kroger_food_stores, 2.5).
rating(neighbors_food_n_brews, 5.0).
rating(pappadeaux_seafood_kitchen, 4.0).
rating(d__s_food_mart, 1.0).
rating(milano_halal_pizza, 4.0).
rating(tjs_dawg_house, 5.0).
rating(the_china_express, 3.5).
rating(the_wine_authority, 5.0).
rating(chickfila, 3.5).
rating(zdar_market, 4.0).
rating(el_patron_tacos_y_tortas, 3.5).
rating(subway, 4.0).
rating(baskinrobbins, 3.5).
rating(bilad_restaurant__bakery, 4.0).
rating(tuscany_italian_bistro, 3.5).
rating(albidel_restaurant__bakery, 2.0).
rating(honey_donuts, 5.0).
rating(saigon_noodle__steak_house, 4.0).
rating(mantra_leaf_cafe, 4.5).
rating(saigon_block, 4.0).
rating(chase_place, 4.0).
rating(sababa_mediterranean_cuisine, 4.0).
rating(sonic_drivein, 1.5).
rating(free_play_arcade, 4.5).
rating(wizards_sports_cafe, 3.5).
rating(saras_market__bakery, 4.5).
rating(s_grill, 5.0).
rating(seven_eleven, 2.0).
rating(owens_country_sausage, 2.5).
rating(kfc, 2.0).
rating(chili_gordos_mexican_cafe, 3.0).
rating(mcdonalds, 2.0).
rating(bunkies_doughnuts, 5.0).
rating(dos_arroyos_comida_casera, 4.0).
rating(sweet_firefly, 4.5).
rating(magic_cup, 4.0).
rating(feng_cha_teahouse, 4.5).
rating(the_fifth_fireside_patio_and_bar, 4.0).
rating(dos_arroyos_comida_casera, 3.0).
rating(starbucks, 2.5).
rating(cvs_pharmacy, 3.0).
rating(al_nimer_roastery, 4.5).
rating(shadys_burger_joint, 4.0).
rating(sopranos_pizza__subs, 3.0).
rating(starbucks, 2.5).
rating(waffle_house, 3.0).
rating(jack_in_the_box, 1.5).
rating(plant_b, 3.0).
rating(omg_tacos, 4.0).
rating(dog_haus_biergarten, 4.0).
rating(walgreens, 3.0).
rating(quiktrip, 3.0).
rating(shipley_donuts, 4.0).
rating(cicis, 1.5).
rating(latinos_bakery, 5.0).
rating(wendys, 2.0).
rating(texadelphia, 3.5).
rating(pokeworks, 4.5).
rating(popbar, 4.0).
rating(xin_xian, 3.0).
rating(new_china, 2.5).
rating(the_halal_guys, 3.5).
rating(wingstop, 3.5).
rating(la_paloma, 1.5).
rating(sonic_drivein, 2.0).
rating(bleachers_sports_grill, 3.0).
rating(fish_n_tails_oyster_bar, 3.5).
rating(tantuni_mediterranean_grill, 4.0).
rating(texaco_garland, 1.0).
rating(taqueria_garcias, 4.5).
rating(davids_meat_market, 4.5).
rating(egg_roll_cafe, 3.0).
rating(cvs_pharmacy, 1.5).
rating(judys_cafe, 4.0).
rating(chilis, 3.0).
rating(desperados_mexican_restaurant_dos, 4.0).
rating(picngo, 1.0).
rating(morning_donuts, 3.5).
rating(caprissi_pizza__pasta, 4.0).
rating(jasons_deli, 1.0).
rating(taqueria_chimalhuacan, 4.5).
rating(taco_bueno, 3.5).
rating(sweet_shoppe_dfw, 5.0).
rating(subway_restaurants, 3.5).
rating(dominos_pizza, 3.5).
rating(no_1_plus_chicken__richardson, 4.5).
rating(gonzos_cocina_mexican_grill, 5.0).
rating(ez_shop, 3.0).
rating(lemma_coffee_roasters, 5.0).
rating(fiesta_mart, 3.5).
rating(the_crab_shed, 3.0).
rating(dominos_pizza, 2.0).
rating(cvs_pharmacy, 1.5).
rating(indulgent_treats, 5.0).
rating(donut_depot, 4.0).
rating(exxon, 2.0).
rating(joy_kitchen, 4.5).
rating(spring_valley_mart, 3.0).
rating(subway, 2.5).
rating(lees_sandwiches, 3.5).
rating(mi_casita_taqueria, 1.0).
rating(jack_in_the_box, 2.0).
rating(student_union_dining_hall, 2.0).
rating(dashin_grocery__4, 4.0).
rating(frutazo_juice_bar__fruteria, 4.5).
rating(nanas_country_citchen__catering, 4.0).
rating(hot_crab, 4.0).
rating(sf_supermarket, 5.0).
rating(m__v_quan, 5.0).
rating(cha_bong_1, 4.0).
rating(banh_mi_1, 3.0).
rating(chao_vit_thanh_da, 3.5).
rating(sieu_thi_thuan_phat, 2.5).
rating(saigon_quan, 4.5).
rating(de_nhat_kho_bo, 4.0).
rating(noodlelicious, 3.5).
rating(seven_eleven, 1.0).
rating(hu_tieu_my_tho_restaurant, 3.5).
rating(quoc_huong_restaurant, 3.5).
rating(panda_express, 2.5).
rating(moes_southwest_grill, 3.0).
rating(ihop, 3.5).
rating(bone_daddys, 3.5).
rating(art_bakery, 3.5).
rating(saigon_cha_lua, 5.0).
rating(asian_buffet, 2.5).
rating(nam_hua_vietnamese_cusine, 3.5).
rating(bbq_king_restaurant, 3.5).
rating(cvs_pharmacy, 3.0).
rating(subway, 3.5).
rating(starbucks, 3.5).
rating(tasty_egg_roll, 3.0).
rating(taqueria_garcias, 5.0).
rating(boba_heaven, 4.0).
rating(subway, 2.5).
rating(razzoos_cajun_cafe, 3.5).
rating(new_texas_king_zabiha_halal_meat_market, 3.0).
rating(roma_palace, 3.5).
rating(subzi_mandi, 2.5).
rating(darrens_american_grill, 4.0).
rating(marcos_pizza, 4.0).
rating(chickfila, 3.5).
rating(banh_cuon_thang_long, 3.5).
rating(seor_chachote_cantina__grill, 4.5).
rating(besas_italian_restaurant, 4.5).
rating(frankies_mexican_cuisine, 4.0).
rating(frankies_place, 4.5).
rating(einstein_bros_bagels, 2.0).
rating(las_flamas_mexican_kitchen, 2.5).
rating(tom_thumb_food__pharmacy, 3.0).
rating(new_orleans, 4.0).
rating(habesha_ethiopian_coffee, 5.0).
rating(ding_tea_garland, 4.5).
rating(papa_murphys, 4.0).
rating(starbucks, 3.0).
rating(tom_yum_thai, 4.0).
rating(studio_movie_grill, 2.5).
rating(modern_market_eatery, 3.5).
rating(luna_grill, 4.0).
rating(pei_wei, 2.5).
rating(smashburger, 3.0).
rating(wendys, 2.5).
rating(la_michoacana_meat_market, 4.5).
rating(tonys_mexican_cocina, 5.0).
rating(smashburger, 2.5).
rating(ihop, 2.0).
rating(whole_foods_market_city_line, 3.0).
rating(sonic_drivein, 1.5).
rating(piada_italian_street_food, 4.0).
rating(cvs_pharmacy, 2.5).
rating(fish_city_grill, 4.5).
rating(pho_is_for_lovers, 4.0).
rating(super_chix, 4.0).
rating(tri_tip_grill, 4.0).
rating(grizzly_burger_house, 5.0).
rating(burgerim, 3.5).
rating(good_union_urban_bbq, 4.0).
rating(shuck_n_jive, 3.0).
rating(jcs_burger_house, 3.5).
rating(donut_palace, 4.0).
rating(american_tap_room, 4.0).
rating(dangki_fusion, 5.0).
rating(fat_straws, 4.5).
rating(fernandos_mexican_cuisine, 3.5).
rating(walmart_supercenter, 2.0).
rating(edoko_sushi__robata, 4.5).
rating(sonny_bryans_smokehouse__richardson, 3.5).
rating(jaspers_richardson, 4.0).
rating(northside_drafthouse__eatery, 4.0).
rating(chard_southeast_asian_kitchen, 4.0).
rating(panda_express, 2.0).
rating(red_mango, 2.0).
rating(nestle_toll_house_cafe_by_chip, 2.5).
rating(mooyah_burgers_fries__shakes, 2.5).
rating(tricky_fish, 4.5).
rating(coolgreens, 4.5).
rating(ediths_neighborhood_bistro, 3.5).
rating(jimmy_johns, 2.5).
rating(panda_express, 2.5).
rating(delish_bubble_tea, 3.5).
rating(pinto_urban_thai_diner, 4.0).
rating(chopped_halal_grill, 4.5).
rating(dipped, 5.0).
rating(starbucks, 3.5).
rating(seven_eleven, 4.0).
rating(braums_ice_cream_and_dairy_store, 3.5).
rating(el_charritos_taqueria, 4.5).
rating(world_food_warehouse, 3.0).
rating(hong_kong_bakery, 2.0).
rating(walnut_food_mart, 1.0).
rating(tamalera_nuevo_len, 5.0).
rating(korys_deli, 1.5).
rating(dennys, 2.5).
rating(hong_kong_che, 3.0).
rating(la_me, 4.0).
rating(doa_maria, 5.0).
rating(dire_dawa_cafe__restaurant, 4.0).
rating(hong_kong_market, 3.0).
rating(mustang_softball_concessions, 5.0).
rating(golden_chick, 3.0).
rating(sprouts_farmers_market, 4.0).
rating(bistro_b, 3.5).
rating(dvegan, 4.5).
rating(papa_johns_pizza, 2.0).
rating(b__p_snacks, 5.0).
rating(tx_nutrition, 5.0).
rating(golden_crown, 3.0).
rating(olive_tree_specialty_foods, 4.0).
rating(shahrzad_mediterranean_market__grill, 4.0).
rating(pho_95, 3.5).
rating(ice_house_beverages, 4.0).
rating(louis_pizza, 4.5).
rating(twenty_fourhour_pizza, 4.0).
rating(tuyet_tofu, 4.5).
rating(i_love_donuts, 4.5).
rating(albertsons, 2.5).
rating(the_string_bean, 3.5).
rating(subway, 3.0).
rating(the_crab_station__dallas, 4.0).
rating(natural_health_shop, 4.0).
rating(lucky_bamboo_kitchen, 4.5).
rating(gojo_ethiopian_restaurant, 3.0).
rating(euro_delicatessen, 4.0).
rating(the_brasa_bar__grill, 4.5).
rating(tom_thumb, 2.5).
rating(griffs_hamburgers, 3.5).
rating(masala_wok, 3.0).
rating(akaya_sushi_izakaya__ramen, 4.5).
rating(papa_murphys, 4.0).
rating(wingstop, 2.5).
rating(lola_tamales__bakery, 4.0).
rating(monta_ramen, 3.5).
rating(cafe_gecko, 4.0).
rating(sugarless_delite, 4.5).
rating(la_madeleine_french_bakery__cafe, 3.0).
rating(kroger, 2.5).
rating(milk_and_honey, 4.5).
rating(starbucks, 2.5).
rating(feng_cha__garland, 4.5).
rating(starbucks, 2.5).
rating(mama_delucas, 4.5).
rating(fish__fizz, 4.5).
rating(cafe_amore, 4.0).
rating(collin_ridge_deli_shop, 5.0).
rating(cappuccino_italian_bistro, 4.0).
rating(long_time_ago, 3.5).
rating(subway, 3.0).
rating(star_food_mart, 4.0).
rating(donut, 5.0).
rating(burger_island, 4.0).
rating(subway, 1.5).
rating(shuri, 3.0).
rating(starbucks, 3.0).
rating(pei_wei, 2.0).
rating(palios_pizza_cafe__richardson, 4.0).
rating(einstein_bros_bagels, 2.5).
rating(taqueria_candelaria, 3.5).
rating(brizo, 4.0).
rating(homebrew_headquarters_inc, 5.0).
rating(taqueria_la_candelaria, 2.5).
rating(pollo_campero, 3.5).
rating(sweet_frog_premium_frozen_yogurt, 3.5).
rating(rodeo_goat, 4.0).
rating(mi_cocina, 3.0).
rating(wingbucket, 4.0).
rating(ino_japanese_restaurant, 4.0).
rating(bambu_asian_cuisine, 4.0).
rating(whataburger, 2.5).
rating(monster_yogurt, 4.0).
rating(reverie_bakeshop, 4.5).
rating(qdoba_mexican_eats, 3.0).
rating(little_greek__richardson, 4.0).
rating(jersey_mikes_subs, 3.5).
rating(jalapeno_mexican_grill, 1.0).
rating(tom_thumb, 3.0).
rating(walmart_supercenter, 2.0).
rating(flying_fish, 3.5).
rating(saltgrass_steak_house, 3.5).
rating(starbucks, 2.5).
rating(masons_cafe, 2.5).
rating(walgreens, 1.5).
rating(mcdonalds, 1.5).
rating(imperial_cuisine, 3.5).
rating(pizza_hut, 2.0).
rating(tacos_el_vale, 3.0).
rating(jcs_burger_bar, 3.5).
rating(jasons_deli, 3.5).
rating(richardson_farmers_market, 3.5).
rating(high_priestess_tea_company, 5.0).
rating(bund_wok_plano, 3.5).
rating(thai_soon_restaurant, 4.0).
rating(tacos_y_mas, 3.5).
rating(golden_star_donuts, 4.5).
rating(mooyah_burgers_fries__shakes, 3.0).
rating(la_michoacana_meat_market, 2.5).
rating(the_popcorn_shack, 4.5).
rating(campisis_restaurant__coit__campbell, 3.0).
rating(curry_bliss, 4.5).
rating(dunkin, 2.0).
rating(baskinrobbins, 1.0).
rating(subway, 2.5).
rating(mooya_burger, 2.5).
rating(salata, 4.5).
rating(gnc, 4.0).
rating(dickeys_barbecue_pit, 3.0).
rating(angel_chicken_kitchen, 4.5).
rating(big_shucks_oyster_bar, 3.5).
rating(cerveceria_el_rancho, 4.5).
rating(dairy_queen, 2.5).
rating(chickfila, 3.5).
rating(raising_canes_chicken_fingers, 3.5).
rating(little_caesars_pizza, 2.0).
rating(texas, 4.0).
rating(marrosso_cafe, 4.5).
rating(captain_daves_seafood_market, 3.5).
rating(quiktrip, 3.0).
rating(sweetwaters_coffee__tea_shire_blvd, 4.5).
rating(rockfish_seafood_grill, 3.5).
rating(shared_table_coffee, 5.0).
rating(starbucks, 3.0).
rating(shopngo, 1.0).
rating(la_picosa, 3.5).
rating(elotes_fanny, 4.5).
rating(great_wall, 3.5).
rating(great_wall_super_buffet, 3.0).
rating(chipotle_mexican_grill, 3.5).
rating(grocery_services_north, 4.0).
rating(cvs_pharmacy, 1.0).
rating(hippo, 4.0).
rating(jack_in_the_box, 2.5).
rating(liberty_burger__richardson, 4.0).
rating(walgreens, 2.0).
rating(corner_bakery_cafe, 3.0).
rating(plano_beverage, 1.0).
rating(alma_liquor__market, 1.0).
rating(cafe_619, 4.5).
rating(deep_cuts, 5.0).
rating(anayas_seafood_scratch_kitchen, 5.0).
rating(ye_shire_tavern, 3.5).
rating(chilis, 3.0).
rating(kosher_palate, 4.5).
rating(popeyes_louisiana_kitchen, 2.0).
rating(cindis_ny_deli__restaurant, 4.0).
rating(johns_cafe, 3.5).
rating(mannys_uptown_texmex, 3.5).
rating(racetrac, 3.5).
rating(sushi_rock, 4.5).
rating(m_t_a_shaved_ice, 4.5).
rating(lovers_egg_roll, 3.0).
rating(mcalisters_deli, 3.5).
rating(thais_thumbz, 4.0).
rating(donut_palace, 5.0).
rating(lima_taverna, 4.5).
rating(southern_recipes_grill, 3.0).
rating(sushi_go, 4.5).
rating(roman_cucina, 4.5).
rating(pizza_hut, 2.5).
rating(love_and_war_in_texas, 3.5).
rating(apollonias, 4.0).
rating(silver_fox_steakhouse, 4.0).
rating(jaimes_donuts, 4.0).
rating(gnc, 3.0).
rating(fino_restaurant__catering, 3.5).
rating(smoothie_factory, 4.0).
rating(kroger, 2.5).
rating(quiktrip, 4.5).
rating(olive_garden_italian_restaurant, 3.0).
rating(the_urban_grill, 4.0).
rating(jersey_mikes_subs, 3.5).
rating(jersey_mikes_subs, 3.5).
rating(total_wine__more, 3.5).
rating(carmines_pizzeria, 3.0).
rating(jupiter_china, 4.0).
rating(seven_eleven, 1.0).
rating(tetco, 2.0).
rating(mcdonalds, 1.0).
rating(cvs_pharmacy, 5.0).
rating(seven_eleven, 2.5).
rating(chinos_tacos, 3.5).
rating(pizza_patrn, 2.0).
rating(tandoori_pizza, 4.0).
rating(hot_pancakes, 4.0).
rating(hooters, 3.0).
rating(starbucks, 2.0).
rating(hooties_burger_bar, 1.0).
rating(mr_wongs_chicken__rice, 3.5).
rating(jack_in_the_box, 3.0).
rating(taqueria_y_restaurante_el_paisano, 3.0).
rating(cuquitas_restaurant, 3.5).
rating(chevron_mart, 1.5).
rating(la_salsa_verde_taqueria, 4.0).
rating(donuts, 5.0).
rating(simons_sushi, 4.0).
rating(el_fenix, 3.5).
rating(pho_s_cowboys, 4.0).
rating(chocolate_angel_cafe__tea_room__high_street, 4.0).
rating(phuong_nam_restaurant, 4.0).
rating(kezira_cafe, 4.0).
rating(noodle_wave, 4.0).
rating(burger_king, 1.5).
rating(fiesta_mart, 3.0).
rating(taco_bueno, 3.5).
rating(shishkabobs_cafe, 4.0).
rating(pho_ca_dao, 2.5).
rating(jack_in_the_box, 4.0).
rating(my_canh_chinese_restaurant, 3.5).
rating(parripollo_country, 1.0).
rating(pollo_regio, 2.5).
rating(hiep_phong_bbq, 3.5).
rating(baleadas_by_lilis, 3.0).
rating(nunos_tacos__vegmex_grill, 4.5).
rating(paleteria_san_marcos, 4.0).
rating(q_w_b, 2.0).
rating(cicis, 3.0).
rating(circle_k, 1.0).
rating(highland_springs, 1.0).
rating(churchs_chicken, 2.0).
rating(chu_chu_grocery_spices__catering, 3.0).
rating(burger_king, 2.0).
rating(jupiter_liquor, 2.5).
rating(kim_ninh_bakery, 4.5).
rating(chu_chu_grocery, 5.0).
rating(woo_mee_ok_korean_bbq, 4.5).
rating(popeyes_louisiana_kitchen, 1.5).
rating(the_boiling_crab, 4.0).
rating(bida_rang_dong, 3.5).
rating(ice_vendors, 3.0).
rating(el_rancho, 4.0).
rating(e__s_grocery, 4.5).
rating(charcoal_avenue, 4.0).
rating(quick_shop, 4.5).
rating(tejano_bbq__more, 4.5).
rating(mcdonalds, 2.0).
rating(tikka_n_kabab, 4.0).
rating(genghis_grill, 3.0).
rating(la_paloma_taqueria, 3.5).
rating(in_the_mix_bakery, 2.0).
rating(burger_king, 1.5).
rating(gnc, 3.0).
rating(eggroll_express, 3.0).
rating(jasons_deli, 4.0).
rating(candy_land, 1.0).
rating(aldeez_caribbean_restaurant__event_center, 3.5).
rating(northpoint_fresh_market_deli, 2.0).
rating(ihop, 2.5).
rating(southwest_farmers_market, 4.5).
rating(corner_food_mart, 4.0).
rating(cafe_mouyyad, 1.0).
rating(taco_bueno, 2.5).
rating(panera_bread, 2.5).
rating(c_store_no_11, 2.0).
rating(philly_connection, 4.0).
rating(taqueria_la_casita, 4.5).
rating(waffle_house, 2.5).
rating(angels_beverage_center, 4.5).
rating(la_poblanita_mexican_bakery, 3.5).
rating(master_wok, 4.0).
rating(tortilleria_la_nueva_puntada, 5.0).
rating(nest_burger, 4.5).
rating(schlotzskys, 2.5).
rating(kayio, 3.0).
rating(outback_steakhouse, 3.5).
rating(red_lobster, 3.0).
rating(enchiladas_restaurant__catering, 1.0).
rating(chipotle_mexican_grill, 3.0).
rating(souper_salad, 2.0).
rating(guanaquitas, 5.0).
rating(wok_express, 3.5).
rating(one_stop_food_store, 4.0).
rating(olive_garden_italian_restaurant, 3.0).
rating(pangea_restaurant__bar, 4.5).
rating(saigon_world_bakery, 4.0).
rating(garden_restaurant, 3.5).
rating(dong_hai_chinese_restaurant, 4.5).
rating(pizza_hut, 2.5).
rating(sonic_drivein, 2.5).
rating(pho_bang_restaurant, 4.0).
rating(aqua_fresh_water_store, 3.0).
rating(pollo_regio, 2.5).
rating(aldi, 3.0).
rating(dong_que, 4.0).
rating(truong_nguyen_market, 3.0).
rating(viet_tofu, 3.0).
rating(northcreek_sandwich_shop, 4.0).
rating(qq_cafe, 2.0).
rating(la_xanh_restaurant, 3.5).
rating(daylight_donuts, 5.0).
rating(truong_nguyen, 1.0).
rating(sharks_fish__chicken, 3.5).
rating(taqueria_el_sabroso, 4.0).
rating(tokyo_harbor, 4.5).
rating(first_chinese_bbq, 2.5).
rating(paesanos_cafe, 4.5).
rating(i_love_egg_rolls, 3.0).
rating(taco_casa, 3.0).
rating(circle_k, 1.0).
rating(scooters_coffee, 4.5).
rating(kazys_gourmet_shop, 4.0).
rating(the_sushi_bar, 4.0).
rating(banh_trang_tron_dallas, 3.5).
rating(kickin_crab, 4.5).
rating(villa_monterrey_restaurant, 4.0).
rating(golden_chick, 4.0).
rating(sayaka_steak__sushi, 4.0).
rating(paleteria_super_smash_ice_cream_and_shaved_ice, 4.5).
rating(tocotoco_boba_tea, 4.5).
rating(bien_xanh, 5.0).
rating(bjs_restaurant__brewhouse, 3.0).
rating(racetrac, 4.0).
rating(pho_21_noodles__grills, 2.5).
rating(la_paloma_taqueria, 2.5).
rating(cookies_by_design, 1.0).
rating(lus_kitchen, 2.5).
rating(hu_tieu_nam_vang, 5.0).
rating(a_n_s_fina, 4.0).
rating(taco_cabana, 2.0).
rating(duc_huong_gio_cha, 4.0).
rating(ngon_bistro, 4.0).
rating(hiep_thai_food_store, 3.0).
rating(acn_herbs__eastern_tradition_chinese_herbs, 5.0).
rating(big_mamas_chicken__waffles, 3.5).
rating(doan_restaurant, 3.5).
rating(swadeshi_indian_cuisine, 2.5).
rating(sarahs_caf__panini, 4.0).
rating(ibex_ethiopian_cuisine_and_bar, 3.0).
rating(delicious_deli, 4.0).
rating(bos_chicken__seafood, 4.5).
rating(ba_le_restaurant__bakery, 2.5).
rating(the_dark_chocolate_bakery, 5.0).
rating(egg_stand, 3.0).
rating(pie_flutin_pastries, 5.0).
rating(quoc_bao_bakery, 4.5).
rating(pizza_patrn, 2.5).
rating(e_z_shop, 1.0).
rating(einstein_bros_bagels, 2.5).
rating(seven_eleven, 3.0).
rating(pizza_patrn, 3.5).
rating(fish_n_tails_oyster_bar, 3.5).
rating(tasty_asia_restaurant, 5.0).
rating(tasty_china, 3.5).
rating(grillmasters_meat, 1.0).
rating(golden_chick, 3.0).
rating(chickfila, 2.5).
rating(com_tam_thuan_kieu, 1.5).
rating(la_madeleine_french_bakery__cafe, 3.0).
rating(sky_rocket_burger, 4.5).
rating(hot_and_creamy_donuts, 4.0).
rating(raising_canes_chicken_fingers, 3.5).
rating(central_market, 4.0).
rating(whataburger, 2.0).
rating(kim_lan_food_to_go, 4.0).
rating(kumars__plano, 3.5).
rating(hu_tieu_my_tho, 3.5).
rating(trak_10, 5.0).
rating(quiktrip, 4.5).
rating(tai_zong_si_chuan, 4.0).
rating(taco_express, 3.0).
rating(jack_in_the_box, 2.0).
rating(los_compadres_taqueria, 5.0).
rating(jack_in_the_box, 2.5).
rating(mcdonalds, 1.5).
rating(mcdonalds, 1.5).
rating(mcdonalds, 2.0).
rating(taco_bell, 2.0).
rating(walmart_supercenter, 2.0).
rating(saigon_deli, 3.5).
rating(seven_eleven, 1.0).
rating(la_super_paleteria, 4.5).
rating(wuden_chopsticks, 3.5).
rating(potbelly_sandwich_shop, 4.0).
rating(boston_market, 2.0).
rating(desta_ethiopian_restaurant, 4.0).
rating(kfc, 2.0).
rating(stone_pit_wings, 5.0).
rating(quiktrip, 3.0).
rating(fusion_sichuan_cuisine, 3.5).
rating(el_pollo_loco, 3.5).
rating(daddy_bobs_catfish, 4.5).
rating(urban_rio_cantina__grill, 4.0).
rating(long_john_silvers, 2.5).
rating(grandys, 3.5).
rating(jgs_old_fashioned_hamburgers, 4.0).
rating(fish_shack, 4.0).
rating(on_the_border_mexican_grill__cantina, 3.0).
rating(el_rancho_supermercado, 3.5).
rating(abugeda_grocery, 5.0).
rating(tacqueria_nuevo_len, 3.0).
rating(ostioneria_7_mares, 2.0).
rating(churchs_chicken, 2.0).
rating(sushi_ichiban, 3.5).
rating(retro_taco, 2.0).
rating(williams_chicken, 2.0).
rating(chipotle_mexican_grill, 2.5).
rating(starbucks, 4.0).
rating(normas_cafe, 3.5).
rating(arbys, 2.5).
rating(subway, 2.5).
rating(vivi_bubble_tea, 4.0).
rating(sakura_chinese_bbq, 4.0).
rating(taco_cabana, 1.5).
rating(dantes_italian_eatery, 4.0).
rating(smoothie_king, 3.5).
rating(seven_eleven, 1.5).
rating(wus_super_bowl, 4.5).
rating(starbucks, 4.0).
rating(city_cafe__bakery, 4.5).
rating(captain_ds, 3.0).
rating(starbucks, 4.0).
rating(mcdonalds, 2.5).
rating(whataburger, 3.5).
rating(subway, 2.0).
rating(dominos_pizza, 2.5).
rating(mcdonalds, 2.5).
rating(outback_steakhouse, 3.0).
rating(mcdonalds, 1.5).
rating(eddys_pizza_restaurant, 4.0).
rating(uni_sushi, 4.5).
rating(pink_coffee, 4.5).
rating(kegs__barrels, 3.0).
rating(hub_streat, 3.5).
rating(georgias_farmers_market, 4.5).
rating(garland_cafe, 3.5).
rating(red_seven_convenience_store, 1.0).
rating(morning_donuts, 4.5).
rating(ruang_thai, 4.5).
rating(urban_nutrition_lounge, 4.0).
rating(gogiya, 4.0).
rating(mcdonalds, 2.0).
rating(maries_kitchen, 5.0).
rating(popeyes_louisiana_kitchen, 2.0).
rating(taco_bell, 2.0).
rating(urban_crust, 4.0).
rating(the_fillmore_pub, 3.5).
rating(cvs_pharmacy, 1.5).
rating(burger_bueno, 4.0).
rating(cvs_pharmacy, 1.5).
rating(the_boiling_crab, 3.5).
rating(ye_ole_butcher_shop, 4.5).
rating(cotton_candy_donuts, 4.5).
rating(better_than_sex__a_dessert_restaurant_plano, 4.0).
rating(dickeys_barbecue_pit, 2.5).
rating(fourteeneighteencoffee_house, 4.5).
rating(yegna_juice_bar, 5.0).
rating(gracious_baking, 5.0).
rating(sini_coffee_lounge, 5.0).
rating(taco_bell, 2.0).
rating(viet_quan, 4.5).
rating(wingstop, 2.0).
rating(lockhart_smokehouse, 4.0).
rating(zalat_pizza, 3.5).
rating(the_gelato_cone, 4.5).
rating(taco_chaco_4, 5.0).
rating(rosas_caf__tortilla_factory, 3.0).
rating(fcking_good_pizza, 5.0).
rating(ebesu_robatasushi, 4.5).
rating(trompo_taqueria__burgers, 4.0).
rating(seven_eleven, 3.5).
rating(daylight_donuts, 4.5).
rating(subway, 2.5).
rating(xo_coffee_company, 4.0).
rating(pho_95_restaurant, 2.5).
rating(vickery_park_plano, 4.0).
rating(sams_club, 3.0).
rating(jorgs_cafe_vienna, 4.0).
rating(kfc, 2.0).
rating(sushi_town, 4.5).
rating(apple_spice, 5.0).
rating(kfc, 2.5).
rating(pizza, 3.5).
rating(sarah_emilys_home_baked_cookies, 5.0).
rating(freds_downtown_philly, 4.0).
rating(primo_brothers_pizza, 4.0).
rating(sweetbasil_thai_kitchen__garland, 4.5).
rating(hawaiian_bros, 4.5).
rating(wannaeat_seafood, 5.0).
rating(wingstop, 1.0).
rating(sicilianos_a_taste_of_italy, 3.5).
rating(seven_eleven, 3.0).
rating(bernards_gourmet_foods, 5.0).
rating(lalibela_ethiopian_restaurant, 4.5).
rating(asian_thai_2_go, 4.0).
rating(abyssinia_gebya, 5.0).
rating(in_the_cut_cafe, 5.0).
rating(tlc_vegan_kitchen, 4.5).
rating(good_wings, 4.0).
rating(meat_point, 3.5).
rating(starbucks, 3.5).
rating(ricks_old_fashioned_burgers, 3.5).
rating(burger_king, 2.5).
rating(cafe_biarritz, 3.5).
rating(golden_chick, 3.0).