is_small_business(far_east_pizza).
is_small_business(la_cuisine_cafe).
is_small_business(cafe_max_richardson).
is_small_business(ten50_bbq).
is_small_business(abu_omar_halal).
is_small_business(texas_smokehouse_barbque).
is_small_business(sweet_donuts).
is_small_business(orchard_at_the_office).
is_small_business(andalous_mediterranean_buffet).
is_small_business(buffet_at_international_buddhist_progress_society).
is_small_business(the_house_cafe).
is_small_business(water_drop_teahouse).
is_small_business(four_bullets_brewery).
is_small_business(big_d_kona_ice).
is_small_business(arapaho_deli).
is_small_business(eiland_coffee_roasters).
is_small_business(new_york_eats).
is_small_business(urban_eatz).
is_small_business(sakhuu_thai).
is_small_business(yoshi_shabu_shabu).
is_small_business(bawarchi_biryanis).
is_small_business(the_wingd_nut).
is_small_business(tiffs_treats).
is_small_business(sweet_mix_desserts).
is_small_business(menas_texmex_grill_cantina).
is_small_business(russos_coal_fired_italian_kitchen).
is_small_business(twisted_root_burger__richardson).
is_small_business(velvet_taco_richardson).
is_small_business(dimassis_mediterranean_buffet).
is_small_business(the_great_outdoors_sub_shop).
is_small_business(boots_and_brix).
is_small_business(tapioca_house).
is_small_business(genroku_sushi__grill).
is_small_business(below_40_fresh_kitchen).
is_small_business(mumtaz_indian_restaurant).
is_small_business(aahar_indian_restaurant).
is_small_business(i_fratelli_pizza_richardson).
is_small_business(paris_donuts).
is_small_business(sichuan_king).
is_small_business(canton_chinese_restaurant).
is_small_business(kolache_factory).
is_small_business(freebirds_world_burrito).
is_small_business(spin_pizza).
is_small_business(smoothie_factory).
is_small_business(fox__hound).
is_small_business(the_pie_pop_company).
is_small_business(maru_ramen).
is_small_business(snuffers).
is_small_business(asian_mint).
is_small_business(torchys_tacos).
is_small_business(snappy_salads).
is_small_business(taco_ocho).
is_small_business(nothing_bundt_cakes).
is_small_business(pho_que_huong).
is_small_business(teriyaki_sensei).
is_small_business(tofu_factory_korean_cuisine).
is_small_business(tkk_fried_chicken).
is_small_business(kung_fu_tea).
is_small_business(jeng_chi_restaurant).
is_small_business(eightyfivec_bakery_cafe).
is_small_business(java_land_coffee_haus).
is_small_business(royal_sichuan).
is_small_business(international_bakery__sandwich_bar).
is_small_business(burning_rice).
is_small_business(pho_corner).
is_small_business(good_fortune_supermarket).
is_small_business(bennys_bagels).
is_small_business(palapas_seafood_bar).
is_small_business(cafe_brazil).
is_small_business(masala_twist).
is_small_business(pho_ok).
is_small_business(sushi_sake).
is_small_business(olive_burger__richardson).
is_small_business(spice_n_rice_indian_cuisine).
is_small_business(mein_cuisine).
is_small_business(taiwan_cafe).
is_small_business(vila_brazil_steak_house).
is_small_business(pho_truong).
is_small_business(custer_wok).
is_small_business(ali_baba_mediterranean_grill).
is_small_business(hometown_cafe).
is_small_business(tongue_in_cheek_ice_cream).
is_small_business(chien_garden).
is_small_business(albaghdady_bakery).
is_small_business(lohas_teriyaki).
is_small_business(buy_low_food_mart__beer).
is_small_business(tineo_peruvian_cafe).
is_small_business(pinedas_mexican_cuisine).
is_small_business(burger_island).
is_small_business(cajun_corner).
is_small_business(anatolia_mart).
is_small_business(lonestar_grill__sports_cafe).
is_small_business(tacos_y_mas).
is_small_business(oriental_express).
is_small_business(kebabnkurry).
is_small_business(spring_creek_barbeque).
is_small_business(salvadorian_cuisine).
is_small_business(kasra_persian_restaurant).
is_small_business(austin_avenue_grill__sports_bar).
is_small_business(la_casita_bakeshop).
is_small_business(los_merla_bakery).
is_small_business(zaks_donuts).
is_small_business(trouvi_cookie_company).
is_small_business(cocina_de_mi_casa).
is_small_business(amigos_restaurant).
is_small_business(alon).
is_small_business(holy_frijoles).
is_small_business(pho_long_noodle_and_grill).
is_small_business(hat_creek_burger_company).
is_small_business(the_line).
is_small_business(meat_maniac).
is_small_business(creamy_doughnuts).
is_small_business(grand_cafe).
is_small_business(ken_japanese_bistro).
is_small_business(afrah_restaurant).
is_small_business(vroom_vroom_valero).
is_small_business(ziggys_tavern).
is_small_business(fish_shack).
is_small_business(tavern_on_main_street).
is_small_business(krab_kingz_7).
is_small_business(habibi_cafe).
is_small_business(jasmine_cafe__hookah_lounge).
is_small_business(dallas_king_daddy_ice).
is_small_business(joy_donuts).
is_small_business(indo_pak_super_market).
is_small_business(indo_pak_cafe).
is_small_business(medina_moroccan_and_mediterranean_fusion).
is_small_business(murphys_deli).
is_small_business(yummy_burgers__bbq).
is_small_business(isabellys_sweet_treats).
is_small_business(first_chinese_bbq).
is_small_business(boba_latte).
is_small_business(m2m_bakery).
is_small_business(albaghdady).
is_small_business(lockwood_distilling).
is_small_business(communion_neighborhood_cooperative).
is_small_business(dels_charcoal_burgers).
is_small_business(sultan_caf).
is_small_business(new_world_realty).
is_small_business(fratello_halal_pizza__grill).
is_small_business(chameli).
is_small_business(kings_noodle).
is_small_business(wound_up_cafe).
is_small_business(creamy_taste_of_heaven).
is_small_business(sweetstop).
is_small_business(smoothie_factory).
is_small_business(pho_tay_do).
is_small_business(monkey_king_noodle_company).
is_small_business(first_emperor_chinese_restaurant).
is_small_business(la_burger).
is_small_business(bulldog_katsu).
is_small_business(jamaica_cabana_restaurant).
is_small_business(marias_bakery).
is_small_business(gopal_vegetarian_restaurant).
is_small_business(al_basha_mediterranean_restaurant).
is_small_business(masami).
is_small_business(fish_n_tails_oyster_bar).
is_small_business(kirin_court_chinese_restaurant).
is_small_business(mmch_richardson).
is_small_business(stephanies_kitchen).
is_small_business(richardson_beer__wine).
is_small_business(onetwothree_street_food).
is_small_business(royal_sweets__fast_food).
is_small_business(addis_abeba_ethiopian_restaurant).
is_small_business(abocas_italian_grill).
is_small_business(industrial_pizza__brew).
is_small_business(fusion_vibes_kitchen__bar).
is_small_business(eileens_pralines).
is_small_business(the_chefs_cuisine).
is_small_business(jababae_food_truck).
is_small_business(pho_bac_restaurant).
is_small_business(chiloso_mexican_bistro__richardson).
is_small_business(cafe_cali).
is_small_business(bikaner_sweets).
is_small_business(hot_breads).
is_small_business(one_hummus).
is_small_business(victor_hugos).
is_small_business(vegvana).
is_small_business(porta_di_roma).
is_small_business(bangkok_at_beltline).
is_small_business(parks_donuts).
is_small_business(dos_charros_restaurant).
is_small_business(glory_chinese_restaurant).
is_small_business(olive_oils_pizzeria).
is_small_business(gong_cha).
is_small_business(fuzzys_taco_shop).
is_small_business(i_love_u_alatte).
is_small_business(sweet_daze_dessert_bar).
is_small_business(alamo_drafthouse_cinema_richardson).
is_small_business(cake_carousel).
is_small_business(cinnaholic).
is_small_business(flaming_buffet).
is_small_business(haystack_burgers__barley).
is_small_business(rickys_hot_chicken).
is_small_business(cream_and_crepes_cafe).
is_small_business(guitars__growlers).
is_small_business(hoki_poki).
is_small_business(ding_tea__richardson).
is_small_business(mezza_cafe).
is_small_business(tasty_tails).
is_small_business(campbell_donuts).
is_small_business(woody_bs_mesquite_bbq).
is_small_business(india_bazaar).
is_small_business(cafe_bleu).
is_small_business(docs_food_store).
is_small_business(chocolate_angel_cafe__tea_room).
is_small_business(pho_pasteur).
is_small_business(el_pollo_loco).
is_small_business(golden_joy_bbq).
is_small_business(thai_asian_fusion_cafe).
is_small_business(sharetea).
is_small_business(waffle_olicious).
is_small_business(natural_grocers).
is_small_business(four_season_farmers_market).
is_small_business(bliss_street_bakery).
is_small_business(bigdash_ice_cream__pastries).
is_small_business(sigels).
is_small_business(pizza_americana).
is_small_business(flaming_skewer).
is_small_business(danang_souphouse).
is_small_business(pappas_catering).
is_small_business(pappasitos_cantina).
is_small_business(roccos_italian_caf).
is_small_business(meteor_hamburgers).
is_small_business(neighbors_food_n_brews).
is_small_business(pappadeaux_seafood_kitchen).
is_small_business(d__s_food_mart).
is_small_business(milano_halal_pizza).
is_small_business(tjs_dawg_house).
is_small_business(the_china_express).
is_small_business(the_wine_authority).
is_small_business(zdar_market).
is_small_business(el_patron_tacos_y_tortas).
is_small_business(bilad_restaurant__bakery).
is_small_business(tuscany_italian_bistro).
is_small_business(albidel_restaurant__bakery).
is_small_business(honey_donuts).
is_small_business(saigon_noodle__steak_house).
is_small_business(mantra_leaf_cafe).
is_small_business(saigon_block).
is_small_business(chase_place).
is_small_business(sababa_mediterranean_cuisine).
is_small_business(free_play_arcade).
is_small_business(wizards_sports_cafe).
is_small_business(saras_market__bakery).
is_small_business(s_grill).
is_small_business(owens_country_sausage).
is_small_business(chili_gordos_mexican_cafe).
is_small_business(bunkies_doughnuts).
is_small_business(dos_arroyos_comida_casera).
is_small_business(sweet_firefly).
is_small_business(magic_cup).
is_small_business(feng_cha_teahouse).
is_small_business(the_fifth_fireside_patio_and_bar).
is_small_business(dos_arroyos_comida_casera).
is_small_business(al_nimer_roastery).
is_small_business(shadys_burger_joint).
is_small_business(sopranos_pizza__subs).
is_small_business(plant_b).
is_small_business(omg_tacos).
is_small_business(dog_haus_biergarten).
is_small_business(latinos_bakery).
is_small_business(pokeworks).
is_small_business(popbar).
is_small_business(xin_xian).
is_small_business(new_china).
is_small_business(la_paloma).
is_small_business(bleachers_sports_grill).
is_small_business(fish_n_tails_oyster_bar).
is_small_business(tantuni_mediterranean_grill).
is_small_business(texaco_garland).
is_small_business(taqueria_garcias).
is_small_business(davids_meat_market).
is_small_business(egg_roll_cafe).
is_small_business(judys_cafe).
is_small_business(desperados_mexican_restaurant_dos).
is_small_business(picngo).
is_small_business(morning_donuts).
is_small_business(caprissi_pizza__pasta).
is_small_business(taqueria_chimalhuacan).
is_small_business(sweet_shoppe_dfw).
is_small_business(no_1_plus_chicken__richardson).
is_small_business(gonzos_cocina_mexican_grill).
is_small_business(ez_shop).
is_small_business(lemma_coffee_roasters).
is_small_business(fiesta_mart).
is_small_business(the_crab_shed).
is_small_business(indulgent_treats).
is_small_business(donut_depot).
is_small_business(joy_kitchen).
is_small_business(spring_valley_mart).
is_small_business(mi_casita_taqueria).
is_small_business(student_union_dining_hall).
is_small_business(dashin_grocery__4).
is_small_business(frutazo_juice_bar__fruteria).
is_small_business(nanas_country_citchen__catering).
is_small_business(hot_crab).
is_small_business(sf_supermarket).
is_small_business(m__v_quan).
is_small_business(cha_bong_1).
is_small_business(banh_mi_1).
is_small_business(chao_vit_thanh_da).
is_small_business(sieu_thi_thuan_phat).
is_small_business(saigon_quan).
is_small_business(de_nhat_kho_bo).
is_small_business(noodlelicious).
is_small_business(hu_tieu_my_tho_restaurant).
is_small_business(quoc_huong_restaurant).
is_small_business(bone_daddys).
is_small_business(art_bakery).
is_small_business(saigon_cha_lua).
is_small_business(asian_buffet).
is_small_business(nam_hua_vietnamese_cusine).
is_small_business(bbq_king_restaurant).
is_small_business(tasty_egg_roll).
is_small_business(taqueria_garcias).
is_small_business(boba_heaven).
is_small_business(razzoos_cajun_cafe).
is_small_business(new_texas_king_zabiha_halal_meat_market).
is_small_business(roma_palace).
is_small_business(subzi_mandi).
is_small_business(darrens_american_grill).
is_small_business(banh_cuon_thang_long).
is_small_business(seor_chachote_cantina__grill).
is_small_business(besas_italian_restaurant).
is_small_business(frankies_mexican_cuisine).
is_small_business(frankies_place).
is_small_business(las_flamas_mexican_kitchen).
is_small_business(tom_thumb_food__pharmacy).
is_small_business(new_orleans).
is_small_business(habesha_ethiopian_coffee).
is_small_business(ding_tea_garland).
is_small_business(tom_yum_thai).
is_small_business(studio_movie_grill).
is_small_business(modern_market_eatery).
is_small_business(luna_grill).
is_small_business(la_michoacana_meat_market).
is_small_business(tonys_mexican_cocina).
is_small_business(whole_foods_market_city_line).
is_small_business(fish_city_grill).
is_small_business(pho_is_for_lovers).
is_small_business(super_chix).
is_small_business(tri_tip_grill).
is_small_business(grizzly_burger_house).
is_small_business(burgerim).
is_small_business(good_union_urban_bbq).
is_small_business(shuck_n_jive).
is_small_business(jcs_burger_house).
is_small_business(donut_palace).
is_small_business(american_tap_room).
is_small_business(dangki_fusion).
is_small_business(fat_straws).
is_small_business(fernandos_mexican_cuisine).
is_small_business(edoko_sushi__robata).
is_small_business(sonny_bryans_smokehouse__richardson).
is_small_business(jaspers_richardson).
is_small_business(northside_drafthouse__eatery).
is_small_business(chard_southeast_asian_kitchen).
is_small_business(red_mango).
is_small_business(tricky_fish).
is_small_business(coolgreens).
is_small_business(ediths_neighborhood_bistro).
is_small_business(delish_bubble_tea).
is_small_business(pinto_urban_thai_diner).
is_small_business(chopped_halal_grill).
is_small_business(dipped).
is_small_business(el_charritos_taqueria).
is_small_business(world_food_warehouse).
is_small_business(hong_kong_bakery).
is_small_business(walnut_food_mart).
is_small_business(tamalera_nuevo_len).
is_small_business(korys_deli).
is_small_business(hong_kong_che).
is_small_business(la_me).
is_small_business(doa_maria).
is_small_business(dire_dawa_cafe__restaurant).
is_small_business(hong_kong_market).
is_small_business(mustang_softball_concessions).
is_small_business(sprouts_farmers_market).
is_small_business(bistro_b).
is_small_business(dvegan).
is_small_business(b__p_snacks).
is_small_business(tx_nutrition).
is_small_business(golden_crown).
is_small_business(olive_tree_specialty_foods).
is_small_business(shahrzad_mediterranean_market__grill).
is_small_business(pho_95).
is_small_business(ice_house_beverages).
is_small_business(louis_pizza).
is_small_business(twenty_fourhour_pizza).
is_small_business(tuyet_tofu).
is_small_business(i_love_donuts).
is_small_business(the_string_bean).
is_small_business(the_crab_station__dallas).
is_small_business(natural_health_shop).
is_small_business(lucky_bamboo_kitchen).
is_small_business(gojo_ethiopian_restaurant).
is_small_business(euro_delicatessen).
is_small_business(the_brasa_bar__grill).
is_small_business(masala_wok).
is_small_business(akaya_sushi_izakaya__ramen).
is_small_business(lola_tamales__bakery).
is_small_business(monta_ramen).
is_small_business(cafe_gecko).
is_small_business(sugarless_delite).
is_small_business(milk_and_honey).
is_small_business(feng_cha__garland).
is_small_business(mama_delucas).
is_small_business(fish__fizz).
is_small_business(cafe_amore).
is_small_business(collin_ridge_deli_shop).
is_small_business(cappuccino_italian_bistro).
is_small_business(long_time_ago).
is_small_business(star_food_mart).
is_small_business(donut).
is_small_business(burger_island).
is_small_business(shuri).
is_small_business(palios_pizza_cafe__richardson).
is_small_business(taqueria_candelaria).
is_small_business(brizo).
is_small_business(homebrew_headquarters_inc).
is_small_business(taqueria_la_candelaria).
is_small_business(rodeo_goat).
is_small_business(mi_cocina).
is_small_business(wingbucket).
is_small_business(ino_japanese_restaurant).
is_small_business(bambu_asian_cuisine).
is_small_business(monster_yogurt).
is_small_business(reverie_bakeshop).
is_small_business(little_greek__richardson).
is_small_business(jalapeno_mexican_grill).
is_small_business(flying_fish).
is_small_business(masons_cafe).
is_small_business(imperial_cuisine).
is_small_business(tacos_el_vale).
is_small_business(jcs_burger_bar).
is_small_business(richardson_farmers_market).
is_small_business(high_priestess_tea_company).
is_small_business(bund_wok_plano).
is_small_business(thai_soon_restaurant).
is_small_business(tacos_y_mas).
is_small_business(golden_star_donuts).
is_small_business(la_michoacana_meat_market).
is_small_business(the_popcorn_shack).
is_small_business(campisis_restaurant__coit__campbell).
is_small_business(curry_bliss).
is_small_business(salata).
is_small_business(angel_chicken_kitchen).
is_small_business(big_shucks_oyster_bar).
is_small_business(cerveceria_el_rancho).
is_small_business(texas).
is_small_business(marrosso_cafe).
is_small_business(captain_daves_seafood_market).
is_small_business(sweetwaters_coffee__tea_shire_blvd).
is_small_business(rockfish_seafood_grill).
is_small_business(shared_table_coffee).
is_small_business(shopngo).
is_small_business(la_picosa).
is_small_business(elotes_fanny).
is_small_business(great_wall).
is_small_business(great_wall_super_buffet).
is_small_business(grocery_services_north).
is_small_business(hippo).
is_small_business(liberty_burger__richardson).
is_small_business(plano_beverage).
is_small_business(alma_liquor__market).
is_small_business(cafe_619).
is_small_business(deep_cuts).
is_small_business(anayas_seafood_scratch_kitchen).
is_small_business(ye_shire_tavern).
is_small_business(kosher_palate).
is_small_business(cindis_ny_deli__restaurant).
is_small_business(johns_cafe).
is_small_business(mannys_uptown_texmex).
is_small_business(sushi_rock).
is_small_business(m_t_a_shaved_ice).
is_small_business(lovers_egg_roll).
is_small_business(thais_thumbz).
is_small_business(donut_palace).
is_small_business(lima_taverna).
is_small_business(southern_recipes_grill).
is_small_business(sushi_go).
is_small_business(roman_cucina).
is_small_business(love_and_war_in_texas).
is_small_business(apollonias).
is_small_business(silver_fox_steakhouse).
is_small_business(jaimes_donuts).
is_small_business(fino_restaurant__catering).
is_small_business(smoothie_factory).
is_small_business(the_urban_grill).
is_small_business(total_wine__more).
is_small_business(carmines_pizzeria).
is_small_business(jupiter_china).
is_small_business(tetco).
is_small_business(chinos_tacos).
is_small_business(tandoori_pizza).
is_small_business(hot_pancakes).
is_small_business(hooties_burger_bar).
is_small_business(mr_wongs_chicken__rice).
is_small_business(taqueria_y_restaurante_el_paisano).
is_small_business(cuquitas_restaurant).
is_small_business(la_salsa_verde_taqueria).
is_small_business(donuts).
is_small_business(simons_sushi).
is_small_business(el_fenix).
is_small_business(pho_s_cowboys).
is_small_business(chocolate_angel_cafe__tea_room__high_street).
is_small_business(phuong_nam_restaurant).
is_small_business(kezira_cafe).
is_small_business(noodle_wave).
is_small_business(fiesta_mart).
is_small_business(shishkabobs_cafe).
is_small_business(pho_ca_dao).
is_small_business(my_canh_chinese_restaurant).
is_small_business(parripollo_country).
is_small_business(pollo_regio).
is_small_business(hiep_phong_bbq).
is_small_business(baleadas_by_lilis).
is_small_business(nunos_tacos__vegmex_grill).
is_small_business(paleteria_san_marcos).
is_small_business(q_w_b).
is_small_business(highland_springs).
is_small_business(chu_chu_grocery_spices__catering).
is_small_business(jupiter_liquor).
is_small_business(kim_ninh_bakery).
is_small_business(chu_chu_grocery).
is_small_business(woo_mee_ok_korean_bbq).
is_small_business(the_boiling_crab).
is_small_business(bida_rang_dong).
is_small_business(ice_vendors).
is_small_business(el_rancho).
is_small_business(e__s_grocery).
is_small_business(charcoal_avenue).
is_small_business(quick_shop).
is_small_business(tejano_bbq__more).
is_small_business(tikka_n_kabab).
is_small_business(la_paloma_taqueria).
is_small_business(in_the_mix_bakery).
is_small_business(eggroll_express).
is_small_business(aldeez_caribbean_restaurant__event_center).
is_small_business(northpoint_fresh_market_deli).
is_small_business(southwest_farmers_market).
is_small_business(corner_food_mart).
is_small_business(cafe_mouyyad).
is_small_business(c_store_no_11).
is_small_business(philly_connection).
is_small_business(taqueria_la_casita).
is_small_business(angels_beverage_center).
is_small_business(la_poblanita_mexican_bakery).
is_small_business(master_wok).
is_small_business(tortilleria_la_nueva_puntada).
is_small_business(nest_burger).
is_small_business(kayio).
is_small_business(enchiladas_restaurant__catering).
is_small_business(guanaquitas).
is_small_business(wok_express).
is_small_business(one_stop_food_store).
is_small_business(pangea_restaurant__bar).
is_small_business(saigon_world_bakery).
is_small_business(garden_restaurant).
is_small_business(dong_hai_chinese_restaurant).
is_small_business(pho_bang_restaurant).
is_small_business(aqua_fresh_water_store).
is_small_business(pollo_regio).
is_small_business(dong_que).
is_small_business(truong_nguyen_market).
is_small_business(viet_tofu).
is_small_business(northcreek_sandwich_shop).
is_small_business(qq_cafe).
is_small_business(la_xanh_restaurant).
is_small_business(daylight_donuts).
is_small_business(truong_nguyen).
is_small_business(sharks_fish__chicken).
is_small_business(taqueria_el_sabroso).
is_small_business(tokyo_harbor).
is_small_business(first_chinese_bbq).
is_small_business(paesanos_cafe).
is_small_business(i_love_egg_rolls).
is_small_business(taco_casa).
is_small_business(scooters_coffee).
is_small_business(kazys_gourmet_shop).
is_small_business(the_sushi_bar).
is_small_business(banh_trang_tron_dallas).
is_small_business(kickin_crab).
is_small_business(villa_monterrey_restaurant).
is_small_business(sayaka_steak__sushi).
is_small_business(paleteria_super_smash_ice_cream_and_shaved_ice).
is_small_business(tocotoco_boba_tea).
is_small_business(bien_xanh).
is_small_business(pho_21_noodles__grills).
is_small_business(la_paloma_taqueria).
is_small_business(lus_kitchen).
is_small_business(a_n_s_fina).
is_small_business(duc_huong_gio_cha).
is_small_business(ngon_bistro).
is_small_business(hiep_thai_food_store).
is_small_business(acn_herbs__eastern_tradition_chinese_herbs).
is_small_business(big_mamas_chicken__waffles).
is_small_business(doan_restaurant).
is_small_business(swadeshi_indian_cuisine).
is_small_business(sarahs_caf__panini).
is_small_business(ibex_ethiopian_cuisine_and_bar).
is_small_business(delicious_deli).
is_small_business(bos_chicken__seafood).
is_small_business(ba_le_restaurant__bakery).
is_small_business(the_dark_chocolate_bakery).
is_small_business(egg_stand).
is_small_business(pie_flutin_pastries).
is_small_business(quoc_bao_bakery).
is_small_business(e_z_shop).
is_small_business(fish_n_tails_oyster_bar).
is_small_business(tasty_asia_restaurant).
is_small_business(tasty_china).
is_small_business(grillmasters_meat).
is_small_business(com_tam_thuan_kieu).
is_small_business(sky_rocket_burger).
is_small_business(hot_and_creamy_donuts).
is_small_business(kim_lan_food_to_go).
is_small_business(kumars__plano).
is_small_business(hu_tieu_my_tho).
is_small_business(tai_zong_si_chuan).
is_small_business(taco_express).
is_small_business(los_compadres_taqueria).
is_small_business(saigon_deli).
is_small_business(la_super_paleteria).
is_small_business(wuden_chopsticks).
is_small_business(desta_ethiopian_restaurant).
is_small_business(stone_pit_wings).
is_small_business(fusion_sichuan_cuisine).
is_small_business(daddy_bobs_catfish).
is_small_business(urban_rio_cantina__grill).
is_small_business(jgs_old_fashioned_hamburgers).
is_small_business(fish_shack).
is_small_business(el_rancho_supermercado).
is_small_business(abugeda_grocery).
is_small_business(tacqueria_nuevo_len).
is_small_business(ostioneria_7_mares).
is_small_business(sushi_ichiban).
is_small_business(retro_taco).
is_small_business(williams_chicken).
is_small_business(normas_cafe).
is_small_business(vivi_bubble_tea).
is_small_business(sakura_chinese_bbq).
is_small_business(dantes_italian_eatery).
is_small_business(wus_super_bowl).
is_small_business(city_cafe__bakery).
is_small_business(eddys_pizza_restaurant).
is_small_business(uni_sushi).
is_small_business(pink_coffee).
is_small_business(kegs__barrels).
is_small_business(hub_streat).
is_small_business(georgias_farmers_market).
is_small_business(garland_cafe).
is_small_business(red_seven_convenience_store).
is_small_business(morning_donuts).
is_small_business(ruang_thai).
is_small_business(urban_nutrition_lounge).
is_small_business(gogiya).
is_small_business(maries_kitchen).
is_small_business(urban_crust).
is_small_business(the_fillmore_pub).
is_small_business(burger_bueno).
is_small_business(the_boiling_crab).
is_small_business(ye_ole_butcher_shop).
is_small_business(cotton_candy_donuts).
is_small_business(better_than_sex__a_dessert_restaurant_plano).
is_small_business(fourteeneighteencoffee_house).
is_small_business(yegna_juice_bar).
is_small_business(gracious_baking).
is_small_business(sini_coffee_lounge).
is_small_business(viet_quan).
is_small_business(lockhart_smokehouse).
is_small_business(zalat_pizza).
is_small_business(the_gelato_cone).
is_small_business(taco_chaco_4).
is_small_business(fcking_good_pizza).
is_small_business(ebesu_robatasushi).
is_small_business(trompo_taqueria__burgers).
is_small_business(daylight_donuts).
is_small_business(xo_coffee_company).
is_small_business(pho_95_restaurant).
is_small_business(vickery_park_plano).
is_small_business(jorgs_cafe_vienna).
is_small_business(sushi_town).
is_small_business(apple_spice).
is_small_business(sarah_emilys_home_baked_cookies).
is_small_business(freds_downtown_philly).
is_small_business(primo_brothers_pizza).
is_small_business(sweetbasil_thai_kitchen__garland).
is_small_business(hawaiian_bros).
is_small_business(wannaeat_seafood).
is_small_business(sicilianos_a_taste_of_italy).
is_small_business(bernards_gourmet_foods).
is_small_business(lalibela_ethiopian_restaurant).
is_small_business(asian_thai_2_go).
is_small_business(abyssinia_gebya).
is_small_business(in_the_cut_cafe).
is_small_business(tlc_vegan_kitchen).
is_small_business(good_wings).
is_small_business(meat_point).
is_small_business(ricks_old_fashioned_burgers).
is_small_business(cafe_biarritz).
